/*
  Name: Data-Module (AllData.js)
  Description: Contains static data for the server.
  Author: Janis Jendraß
  ForVersion: <1.14.X
 */
module.exports = function AllData() {
  this.items = [
    { 'name': 'Acacia Button', 'item': 'acacia_button' },
    { 'name': 'Acacia Door', 'item': 'acacia_door' },
    { 'name': 'Acacia Fence Gate', 'item': 'acacia_fence_gate' },
    { 'name': 'Acacia Fence', 'item': 'acacia_fence' },
    { 'name': 'Acacia Leaves', 'item': 'acacia_leaves' },
    { 'name': 'Acacia Log', 'item': 'acacia_log' },
    { 'name': 'Acacia Planks', 'item': 'acacia_planks' },
    { 'name': 'Acacia Pressure Plate', 'item': 'acacia_pressure_plate' },
    { 'name': 'Acacia Sapling', 'item': 'acacia_sapling' },
    { 'name': 'Acacia Sign', 'item': 'acacia_sign' },
    { 'name': 'Acacia Slab', 'item': 'acacia_slab' },
    { 'name': 'Acacia Stairs', 'item': 'acacia_stairs' },
    { 'name': 'Acacia Trapdoor', 'item': 'acacia_trapdoor' },
    { 'name': 'Acacia Wall Sign', 'item': 'acacia_wall_sign' },
    { 'name': 'Acacia Wood', 'item': 'acacia_wood' },
    { 'name': 'Activator Rail', 'item': 'activator_rail' },
    { 'name': 'Air', 'item': 'air' },
    { 'name': 'Allium', 'item': 'allium' },
    { 'name': 'Andesite', 'item': 'andesite' },
    { 'name': 'Andesite Slab', 'item': 'andesite_slab' },
    { 'name': 'Andesite Stairs', 'item': 'andesite_stairs' },
    { 'name': 'Andesite Wall', 'item': 'andesite_wall' },
    { 'name': 'Anvil', 'item': 'anvil' },
    { 'name': 'Attached Melon Stem', 'item': 'attached_melon_stem' },
    { 'name': 'Attached Pumpkin Stem', 'item': 'attached_pumpkin_stem' },
    { 'name': 'Azure Bluet', 'item': 'azure_bluet' },
    { 'name': 'Bamboo', 'item': 'bamboo' },
    { 'name': 'Bamboo Sapling', 'item': 'bamboo_sapling' },
    { 'name': 'Barrel', 'item': 'barrel' },
    { 'name': 'Barrier', 'item': 'barrier' },
    { 'name': 'Beacon', 'item': 'beacon' },
    { 'name': 'Bedrock', 'item': 'bedrock' },
    { 'name': 'Beetroots', 'item': 'beetroots' },
    { 'name': 'Bell', 'item': 'bell' },
    { 'name': 'Birch Button', 'item': 'birch_button' },
    { 'name': 'Birch Door', 'item': 'birch_door' },
    { 'name': 'Birch Fence Gate', 'item': 'birch_fence_gate' },
    { 'name': 'Birch Fence', 'item': 'birch_fence' },
    { 'name': 'Birch Leaves', 'item': 'birch_leaves' },
    { 'name': 'Birch Log', 'item': 'birch_log' },
    { 'name': 'Birch Planks', 'item': 'birch_planks' },
    { 'name': 'Birch Pressure Plate', 'item': 'birch_pressure_plate' },
    { 'name': 'Birch Sapling', 'item': 'birch_sapling' },
    { 'name': 'Birch Sign', 'item': 'birch_sign' },
    { 'name': 'Birch Slab', 'item': 'birch_slab' },
    { 'name': 'Birch Stairs', 'item': 'birch_stairs' },
    { 'name': 'Birch Trapdoor', 'item': 'birch_trapdoor' },
    { 'name': 'Birch Wall Sign', 'item': 'birch_wall_sign' },
    { 'name': 'Birch Wood', 'item': 'birch_wood' },
    { 'name': 'Black Banner', 'item': 'black_banner' },
    { 'name': 'Black Bed', 'item': 'black_bed' },
    { 'name': 'Black Carpet', 'item': 'black_carpet' },
    { 'name': 'Black Concrete Powder', 'item': 'black_concrete_powder' },
    { 'name': 'Black Concrete', 'item': 'black_concrete' },
    { 'name': 'Black Glazed Terracotta', 'item': 'black_glazed_terracotta' },
    { 'name': 'Black Shulker Box', 'item': 'black_shulker_box' },
    { 'name': 'Black Stained Glass', 'item': 'black_stained_glass' },
    { 'name': 'Black Stained Glass Pane', 'item': 'black_stained_glass_pane' },
    { 'name': 'Black Terracotta', 'item': 'black_terracotta' },
    { 'name': 'Black Wall Banner', 'item': 'black_wall_banner' },
    { 'name': 'Black Wool', 'item': 'black_wool' },
    { 'name': 'Blast Furnace', 'item': 'blast_furnace' },
    { 'name': 'Blue Banner', 'item': 'blue_banner' },
    { 'name': 'Blue Bed', 'item': 'blue_bed' },
    { 'name': 'Blue Carpet', 'item': 'blue_carpet' },
    { 'name': 'Blue Concrete Powder', 'item': 'blue_concrete_powder' },
    { 'name': 'Blue Concrete', 'item': 'blue_concrete' },
    { 'name': 'Blue Glazed Terracotta', 'item': 'blue_glazed_terracotta' },
    { 'name': 'Blue Ice', 'item': 'blue_ice' },
    { 'name': 'Blue Orchid', 'item': 'blue_orchid' },
    { 'name': 'Blue Shulker Box', 'item': 'blue_shulker_box' },
    { 'name': 'Blue Stained Glass', 'item': 'blue_stained_glass' },
    { 'name': 'Blue Stained Glass Pane', 'item': 'blue_stained_glass_pane' },
    { 'name': 'Blue Terracotta', 'item': 'blue_terracotta' },
    { 'name': 'Blue Wall Banner', 'item': 'blue_wall_banner' },
    { 'name': 'Blue Wool', 'item': 'blue_wool' },
    { 'name': 'Bone Block', 'item': 'bone_block' },
    { 'name': 'Bookshelf', 'item': 'bookshelf' },
    { 'name': 'Brain Coral', 'item': 'brain_coral' },
    { 'name': 'Brain Coral Block', 'item': 'brain_coral_block' },
    { 'name': 'Brain Coral Fan', 'item': 'brain_coral_fan' },
    { 'name': 'Brain Coral Wall Fan', 'item': 'brain_coral_wall_fan' },
    { 'name': 'Brewing Stand', 'item': 'brewing_stand' },
    { 'name': 'Brick Slab', 'item': 'brick_slab' },
    { 'name': 'Brick Stairs', 'item': 'brick_stairs' },
    { 'name': 'Brick Wall', 'item': 'brick_wall' },
    { 'name': 'Bricks', 'item': 'bricks' },
    { 'name': 'Brown Banner', 'item': 'brown_banner' },
    { 'name': 'Brown Bed', 'item': 'brown_bed' },
    { 'name': 'Brown Carpet', 'item': 'brown_carpet' },
    { 'name': 'Brown Concrete Powder', 'item': 'brown_concrete_powder' },
    { 'name': 'Brown Concrete', 'item': 'brown_concrete' },
    { 'name': 'Brown Glazed Terracotta', 'item': 'brown_glazed_terracotta' },
    { 'name': 'Brown Mushroom Block', 'item': 'brown_mushroom_block' },
    { 'name': 'Brown Mushroom', 'item': 'brown_mushroom' },
    { 'name': 'Brown Shulker Box', 'item': 'brown_shulker_box' },
    { 'name': 'Brown Stained Glass', 'item': 'brown_stained_glass' },
    { 'name': 'Brown Stained Glass Pane', 'item': 'brown_stained_glass_pane' },
    { 'name': 'Brown Terracotta', 'item': 'brown_terracotta' },
    { 'name': 'Brown Wall Banner', 'item': 'brown_wall_banner' },
    { 'name': 'Brown Wool', 'item': 'brown_wool' },
    { 'name': 'Bubble Column', 'item': 'bubble_column' },
    { 'name': 'Bubble Coral', 'item': 'bubble_coral' },
    { 'name': 'Bubble Coral Block', 'item': 'bubble_coral_block' },
    { 'name': 'Bubble Coral Fan', 'item': 'bubble_coral_fan' },
    { 'name': 'Bubble Coral Wall Fan', 'item': 'bubble_coral_wall_fan' },
    { 'name': 'Cactus', 'item': 'cactus' },
    { 'name': 'Cake', 'item': 'cake' },
    { 'name': 'Campfire', 'item': 'campfire' },
    { 'name': 'Carrots', 'item': 'carrots' },
    { 'name': 'Cartography Table', 'item': 'cartography_table' },
    { 'name': 'Carved Pumpkin', 'item': 'carved_pumpkin' },
    { 'name': 'Cauldron', 'item': 'cauldron' },
    { 'name': 'Cave Air', 'item': 'cave_air' },
    { 'name': 'Chain Command Block', 'item': 'chain_command_block' },
    { 'name': 'Chest', 'item': 'chest' },
    { 'name': 'Chipped Anvil', 'item': 'chipped_anvil' },
    { 'name': 'Chiseled Quartz Block', 'item': 'chiseled_quartz_block' },
    { 'name': 'Chiseled Red Sandstone', 'item': 'chiseled_red_sandstone' },
    { 'name': 'Chiseled Sandstone', 'item': 'chiseled_sandstone' },
    { 'name': 'Chiseled Stone Bricks', 'item': 'chiseled_stone_bricks' },
    { 'name': 'Chorus Flower', 'item': 'chorus_flower' },
    { 'name': 'Chorus Plant', 'item': 'chorus_plant' },
    { 'name': 'Clay', 'item': 'clay' },
    { 'name': 'Block of Coal', 'item': 'coal_block' },
    { 'name': 'Coal Ore', 'item': 'coal_ore' },
    { 'name': 'Coarse Dirt', 'item': 'coarse_dirt' },
    { 'name': 'Cobblestone', 'item': 'cobblestone' },
    { 'name': 'Cobblestone Slab', 'item': 'cobblestone_slab' },
    { 'name': 'Cobblestone Stairs', 'item': 'cobblestone_stairs' },
    { 'name': 'Cobblestone Wall', 'item': 'cobblestone_wall' },
    { 'name': 'Cobweb', 'item': 'cobweb' },
    { 'name': 'Cocoa', 'item': 'cocoa' },
    { 'name': 'Command Block', 'item': 'command_block' },
    { 'name': 'Redstone Comparator', 'item': 'comparator' },
    { 'name': 'Composter', 'item': 'composter' },
    { 'name': 'Conduit', 'item': 'conduit' },
    { 'name': 'Cornflower', 'item': 'cornflower' },
    { 'name': 'Cracked Stone Bricks', 'item': 'cracked_stone_bricks' },
    { 'name': 'Crafting Table', 'item': 'crafting_table' },
    { 'name': 'Creeper Head', 'item': 'creeper_head' },
    { 'name': 'Creeper Wall Head', 'item': 'creeper_wall_head' },
    { 'name': 'Cut Red Sandstone', 'item': 'cut_red_sandstone' },
    { 'name': 'Cut Red Sandstone Slab', 'item': 'cut_red_sandstone_slab' },
    { 'name': 'Cut Sandstone', 'item': 'cut_sandstone' },
    { 'name': 'Cut Sandstone Slab', 'item': 'cut_sandstone_slab' },
    { 'name': 'Cyan Banner', 'item': 'cyan_banner' },
    { 'name': 'Cyan Bed', 'item': 'cyan_bed' },
    { 'name': 'Cyan Carpet', 'item': 'cyan_carpet' },
    { 'name': 'Cyan Concrete Powder', 'item': 'cyan_concrete_powder' },
    { 'name': 'Cyan Concrete', 'item': 'cyan_concrete' },
    { 'name': 'Cyan Glazed Terracotta', 'item': 'cyan_glazed_terracotta' },
    { 'name': 'Cyan Shulker Box', 'item': 'cyan_shulker_box' },
    { 'name': 'Cyan Stained Glass', 'item': 'cyan_stained_glass' },
    { 'name': 'Cyan Stained Glass Pane', 'item': 'cyan_stained_glass_pane' },
    { 'name': 'Cyan Terracotta', 'item': 'cyan_terracotta' },
    { 'name': 'Cyan Wall Banner', 'item': 'cyan_wall_banner' },
    { 'name': 'Cyan Wool', 'item': 'cyan_wool' },
    { 'name': 'Damaged Anvil', 'item': 'damaged_anvil' },
    { 'name': 'Dandelion', 'item': 'dandelion' },
    { 'name': 'Dark Oak Button', 'item': 'dark_oak_button' },
    { 'name': 'Dark Oak Door', 'item': 'dark_oak_door' },
    { 'name': 'Dark Oak Fence Gate', 'item': 'dark_oak_fence_gate' },
    { 'name': 'Dark Oak Fence', 'item': 'dark_oak_fence' },
    { 'name': 'Dark Oak Leaves', 'item': 'dark_oak_leaves' },
    { 'name': 'Dark Oak Log', 'item': 'dark_oak_log' },
    { 'name': 'Dark Oak Planks', 'item': 'dark_oak_planks' },
    { 'name': 'Dark Oak Pressure Plate', 'item': 'dark_oak_pressure_plate' },
    { 'name': 'Dark Oak Sapling', 'item': 'dark_oak_sapling' },
    { 'name': 'Dark Oak Sign', 'item': 'dark_oak_sign' },
    { 'name': 'Dark Oak Slab', 'item': 'dark_oak_slab' },
    { 'name': 'Dark Oak Stairs', 'item': 'dark_oak_stairs' },
    { 'name': 'Dark Oak Trapdoor', 'item': 'dark_oak_trapdoor' },
    { 'name': 'Dark Oak Wall Sign', 'item': 'dark_oak_wall_sign' },
    { 'name': 'Dark Oak Wood', 'item': 'dark_oak_wood' },
    { 'name': 'Dark Prismarine', 'item': 'dark_prismarine' },
    { 'name': 'Dark Prismarine Slab', 'item': 'dark_prismarine_slab' },
    { 'name': 'Dark Prismarine Stairs', 'item': 'dark_prismarine_stairs' },
    { 'name': 'Daylight Detector', 'item': 'daylight_detector' },
    { 'name': 'Dead Brain Coral', 'item': 'dead_brain_coral' },
    { 'name': 'Dead Brain Coral Block', 'item': 'dead_brain_coral_block' },
    { 'name': 'Dead Brain Coral Fan', 'item': 'dead_brain_coral_fan' },
    { 'name': 'Dead Brain Coral Wall Fan', 'item': 'dead_brain_coral_wall_fan' },
    { 'name': 'Dead Bubble Coral', 'item': 'dead_bubble_coral' },
    { 'name': 'Dead Bubble Coral Block', 'item': 'dead_bubble_coral_block' },
    { 'name': 'Dead Bubble Coral Fan', 'item': 'dead_bubble_coral_fan' },
    { 'name': 'Dead Bubble Coral Wall Fan', 'item': 'dead_bubble_coral_wall_fan' },
    { 'name': 'Dead Bush', 'item': 'dead_bush' },
    { 'name': 'Dead Fire Coral', 'item': 'dead_fire_coral' },
    { 'name': 'Dead Fire Coral Block', 'item': 'dead_fire_coral_block' },
    { 'name': 'Dead Fire Coral Fan', 'item': 'dead_fire_coral_fan' },
    { 'name': 'Dead Fire Coral Wall Fan', 'item': 'dead_fire_coral_wall_fan' },
    { 'name': 'Dead Horn Coral', 'item': 'dead_horn_coral' },
    { 'name': 'Dead Horn Coral Block', 'item': 'dead_horn_coral_block' },
    { 'name': 'Dead Horn Coral Fan', 'item': 'dead_horn_coral_fan' },
    { 'name': 'Dead Horn Coral Wall Fan', 'item': 'dead_horn_coral_wall_fan' },
    { 'name': 'Dead Tube Coral', 'item': 'dead_tube_coral' },
    { 'name': 'Dead Tube Coral Block', 'item': 'dead_tube_coral_block' },
    { 'name': 'Dead Tube Coral Fan', 'item': 'dead_tube_coral_fan' },
    { 'name': 'Dead Tube Coral Wall Fan', 'item': 'dead_tube_coral_wall_fan' },
    { 'name': 'Detector Rail', 'item': 'detector_rail' },
    { 'name': 'Block of Diamond', 'item': 'diamond_block' },
    { 'name': 'Diamond Ore', 'item': 'diamond_ore' },
    { 'name': 'Diorite', 'item': 'diorite' },
    { 'name': 'Diorite Slab', 'item': 'diorite_slab' },
    { 'name': 'Diorite Stairs', 'item': 'diorite_stairs' },
    { 'name': 'Diorite Wall', 'item': 'diorite_wall' },
    { 'name': 'Dirt', 'item': 'dirt' },
    { 'name': 'Dispenser', 'item': 'dispenser' },
    { 'name': 'Dragon Egg', 'item': 'dragon_egg' },
    { 'name': 'Dragon Head', 'item': 'dragon_head' },
    { 'name': 'Dragon Wall Head', 'item': 'dragon_wall_head' },
    { 'name': 'Dried Kelp Block', 'item': 'dried_kelp_block' },
    { 'name': 'Dropper', 'item': 'dropper' },
    { 'name': 'Block of Emerald', 'item': 'emerald_block' },
    { 'name': 'Emerald Ore', 'item': 'emerald_ore' },
    { 'name': 'Enchanting Table', 'item': 'enchanting_table' },
    { 'name': 'End Gateway', 'item': 'end_gateway' },
    { 'name': 'End Portal Frame', 'item': 'end_portal_frame' },
    { 'name': 'End Portal', 'item': 'end_portal' },
    { 'name': 'End Rod', 'item': 'end_rod' },
    { 'name': 'End Stone', 'item': 'end_stone' },
    { 'name': 'End Stone Brick Slab', 'item': 'end_stone_brick_slab' },
    { 'name': 'End Stone Brick Stairs', 'item': 'end_stone_brick_stairs' },
    { 'name': 'End Stone Brick Wall', 'item': 'end_stone_brick_wall' },
    { 'name': 'End Stone Bricks', 'item': 'end_stone_bricks' },
    { 'name': 'Ender Chest', 'item': 'ender_chest' },
    { 'name': 'Farmland', 'item': 'farmland' },
    { 'name': 'Fern', 'item': 'fern' },
    { 'name': 'Fire', 'item': 'fire' },
    { 'name': 'Fire Coral', 'item': 'fire_coral' },
    { 'name': 'Fire Coral Block', 'item': 'fire_coral_block' },
    { 'name': 'Fire Coral Fan', 'item': 'fire_coral_fan' },
    { 'name': 'Fire Coral Wall Fan', 'item': 'fire_coral_wall_fan' },
    { 'name': 'Fletching Table', 'item': 'fletching_table' },
    { 'name': 'Flower Pot', 'item': 'flower_pot' },
    { 'name': 'Frosted Ice', 'item': 'frosted_ice' },
    { 'name': 'Furnace', 'item': 'furnace' },
    { 'name': 'Glass', 'item': 'glass' },
    { 'name': 'Glass Pane', 'item': 'glass_pane' },
    { 'name': 'Glowstone', 'item': 'glowstone' },
    { 'name': 'Block of Gold', 'item': 'gold_block' },
    { 'name': 'Gold Ore', 'item': 'gold_ore' },
    { 'name': 'Granite', 'item': 'granite' },
    { 'name': 'Granite Slab', 'item': 'granite_slab' },
    { 'name': 'Granite Stairs', 'item': 'granite_stairs' },
    { 'name': 'Granite Wall', 'item': 'granite_wall' },
    { 'name': 'Grass Block', 'item': 'grass_block' },
    { 'name': 'Grass Path', 'item': 'grass_path' },
    { 'name': 'Grass', 'item': 'grass' },
    { 'name': 'Gravel', 'item': 'gravel' },
    { 'name': 'Gray Banner', 'item': 'gray_banner' },
    { 'name': 'Gray Bed', 'item': 'gray_bed' },
    { 'name': 'Gray Carpet', 'item': 'gray_carpet' },
    { 'name': 'Gray Concrete Powder', 'item': 'gray_concrete_powder' },
    { 'name': 'Gray Concrete', 'item': 'gray_concrete' },
    { 'name': 'Gray Glazed Terracotta', 'item': 'gray_glazed_terracotta' },
    { 'name': 'Gray Shulker Box', 'item': 'gray_shulker_box' },
    { 'name': 'Gray Stained Glass', 'item': 'gray_stained_glass' },
    { 'name': 'Gray Stained Glass Pane', 'item': 'gray_stained_glass_pane' },
    { 'name': 'Gray Terracotta', 'item': 'gray_terracotta' },
    { 'name': 'Gray Wall Banner', 'item': 'gray_wall_banner' },
    { 'name': 'Gray Wool', 'item': 'gray_wool' },
    { 'name': 'Green Banner', 'item': 'green_banner' },
    { 'name': 'Green Bed', 'item': 'green_bed' },
    { 'name': 'Green Carpet', 'item': 'green_carpet' },
    { 'name': 'Green Concrete Powder', 'item': 'green_concrete_powder' },
    { 'name': 'Green Concrete', 'item': 'green_concrete' },
    { 'name': 'Green Glazed Terracotta', 'item': 'green_glazed_terracotta' },
    { 'name': 'Green Shulker Box', 'item': 'green_shulker_box' },
    { 'name': 'Green Stained Glass', 'item': 'green_stained_glass' },
    { 'name': 'Green Stained Glass Pane', 'item': 'green_stained_glass_pane' },
    { 'name': 'Green Terracotta', 'item': 'green_terracotta' },
    { 'name': 'Green Wall Banner', 'item': 'green_wall_banner' },
    { 'name': 'Green Wool', 'item': 'green_wool' },
    { 'name': 'Grindstone', 'item': 'grindstone' },
    { 'name': 'Hay Bale', 'item': 'hay_block' },
    { 'name': 'Heavy Weighted Pressure Plate', 'item': 'heavy_weighted_pressure_plate' },
    { 'name': 'Hopper', 'item': 'hopper' },
    { 'name': 'Horn Coral', 'item': 'horn_coral' },
    { 'name': 'Horn Coral Block', 'item': 'horn_coral_block' },
    { 'name': 'Horn Coral Fan', 'item': 'horn_coral_fan' },
    { 'name': 'Horn Coral Wall Fan', 'item': 'horn_coral_wall_fan' },
    { 'name': 'Ice', 'item': 'ice' },
    { 'name': 'Infested Chiseled Stone Bricks', 'item': 'infested_chiseled_stone_bricks' },
    { 'name': 'Infested Cobblestone', 'item': 'infested_cobblestone' },
    { 'name': 'Infested Cracked Stone Bricks', 'item': 'infested_cracked_stone_bricks' },
    { 'name': 'Infested Mossy Stone Bricks', 'item': 'infested_mossy_stone_bricks' },
    { 'name': 'Infested Stone', 'item': 'infested_stone' },
    { 'name': 'Infested Stone Bricks', 'item': 'infested_stone_bricks' },
    { 'name': 'Iron Bars', 'item': 'iron_bars' },
    { 'name': 'Iron Door', 'item': 'iron_door' },
    { 'name': 'Block of Iron', 'item': 'iron_block' },
    { 'name': 'Iron Ore', 'item': 'iron_ore' },
    { 'name': 'Iron Trapdoor', 'item': 'iron_trapdoor' },
    { 'name': "Jack o'Lantern", 'item': 'jack_o_lantern' },
    { 'name': 'Jigsaw Block', 'item': 'jigsaw' },
    { 'name': 'Jukebox', 'item': 'jukebox' },
    { 'name': 'Jungle Button', 'item': 'jungle_button' },
    { 'name': 'Jungle Door', 'item': 'jungle_door' },
    { 'name': 'Jungle Fence Gate', 'item': 'jungle_fence_gate' },
    { 'name': 'Jungle Fence', 'item': 'jungle_fence' },
    { 'name': 'Jungle Leaves', 'item': 'jungle_leaves' },
    { 'name': 'Jungle Log', 'item': 'jungle_log' },
    { 'name': 'Jungle Planks', 'item': 'jungle_planks' },
    { 'name': 'Jungle Pressure Plate', 'item': 'jungle_pressure_plate' },
    { 'name': 'Jungle Sapling', 'item': 'jungle_sapling' },
    { 'name': 'Jungle Sign', 'item': 'jungle_sign' },
    { 'name': 'Jungle Slab', 'item': 'jungle_slab' },
    { 'name': 'Jungle Stairs', 'item': 'jungle_stairs' },
    { 'name': 'Jungle Trapdoor', 'item': 'jungle_trapdoor' },
    { 'name': 'Jungle Wall Sign', 'item': 'jungle_wall_sign' },
    { 'name': 'Jungle Wood', 'item': 'jungle_wood' },
    { 'name': 'Kelp', 'item': 'kelp' },
    { 'name': 'Kelp Plant', 'item': 'kelp_plant' },
    { 'name': 'Ladder', 'item': 'ladder' },
    { 'name': 'Lantern', 'item': 'lantern' },
    { 'name': 'Lapis Lazuli Block', 'item': 'lapis_block' },
    { 'name': 'Lapis Lazuli Ore', 'item': 'lapis_ore' },
    { 'name': 'Large Fern', 'item': 'large_fern' },
    { 'name': 'Lava', 'item': 'lava' },
    { 'name': 'Lectern', 'item': 'lectern' },
    { 'name': 'Lever', 'item': 'lever' },
    { 'name': 'Light Blue Banner', 'item': 'light_blue_banner' },
    { 'name': 'Light Blue Bed', 'item': 'light_blue_bed' },
    { 'name': 'Light Blue Carpet', 'item': 'light_blue_carpet' },
    { 'name': 'Light Blue Concrete Powder', 'item': 'light_blue_concrete_powder' },
    { 'name': 'Light Blue Concrete', 'item': 'light_blue_concrete' },
    { 'name': 'Light Blue Glazed Terracotta', 'item': 'light_blue_glazed_terracotta' },
    { 'name': 'Light Blue Shulker Box', 'item': 'light_blue_shulker_box' },
    { 'name': 'Light Blue Stained Glass', 'item': 'light_blue_stained_glass' },
    { 'name': 'Light Blue Stained Glass Pane', 'item': 'light_blue_stained_glass_pane' },
    { 'name': 'Light Blue Terracotta', 'item': 'light_blue_terracotta' },
    { 'name': 'Light Blue Wall Banner', 'item': 'light_blue_wall_banner' },
    { 'name': 'Light Blue Wool', 'item': 'light_blue_wool' },
    { 'name': 'Light Gray Banner', 'item': 'light_gray_banner' },
    { 'name': 'Light Gray Bed', 'item': 'light_gray_bed' },
    { 'name': 'Light Gray Carpet', 'item': 'light_gray_carpet' },
    { 'name': 'Light Gray Concrete Powder', 'item': 'light_gray_concrete_powder' },
    { 'name': 'Light Gray Concrete', 'item': 'light_gray_concrete' },
    { 'name': 'Light Gray Glazed Terracotta', 'item': 'light_gray_glazed_terracotta' },
    { 'name': 'Light Gray Shulker Box', 'item': 'light_gray_shulker_box' },
    { 'name': 'Light Gray Stained Glass', 'item': 'light_gray_stained_glass' },
    { 'name': 'Light Gray Stained Glass Pane', 'item': 'light_gray_stained_glass_pane' },
    { 'name': 'Light Gray Terracotta', 'item': 'light_gray_terracotta' },
    { 'name': 'Light Gray Wall Banner', 'item': 'light_gray_wall_banner' },
    { 'name': 'Light Gray Wool', 'item': 'light_gray_wool' },
    { 'name': 'Light Weighted Pressure Plate', 'item': 'light_weighted_pressure_plate' },
    { 'name': 'Lilac', 'item': 'lilac' },
    { 'name': 'Lily Pad', 'item': 'lily_pad' },
    { 'name': 'Lily of the Valley', 'item': 'lily_of_the_valley' },
    { 'name': 'Lime Banner', 'item': 'lime_banner' },
    { 'name': 'Lime Bed', 'item': 'lime_bed' },
    { 'name': 'Lime Carpet', 'item': 'lime_carpet' },
    { 'name': 'Lime Concrete Powder', 'item': 'lime_concrete_powder' },
    { 'name': 'Lime Concrete', 'item': 'lime_concrete' },
    { 'name': 'Lime Glazed Terracotta', 'item': 'lime_glazed_terracotta' },
    { 'name': 'Lime Shulker Box', 'item': 'lime_shulker_box' },
    { 'name': 'Lime Stained Glass', 'item': 'lime_stained_glass' },
    { 'name': 'Lime Stained Glass Pane', 'item': 'lime_stained_glass_pane' },
    { 'name': 'Lime Terracotta', 'item': 'lime_terracotta' },
    { 'name': 'Lime Wall Banner', 'item': 'lime_wall_banner' },
    { 'name': 'Lime Wool', 'item': 'lime_wool' },
    { 'name': 'Loom', 'item': 'loom' },
    { 'name': 'Magenta Banner', 'item': 'magenta_banner' },
    { 'name': 'Magenta Bed', 'item': 'magenta_bed' },
    { 'name': 'Magenta Carpet', 'item': 'magenta_carpet' },
    { 'name': 'Magenta Concrete Powder', 'item': 'magenta_concrete_powder' },
    { 'name': 'Magenta Concrete', 'item': 'magenta_concrete' },
    { 'name': 'Magenta Glazed Terracotta', 'item': 'magenta_glazed_terracotta' },
    { 'name': 'Magenta Shulker Box', 'item': 'magenta_shulker_box' },
    { 'name': 'Magenta Stained Glass', 'item': 'magenta_stained_glass' },
    { 'name': 'Magenta Stained Glass Pane', 'item': 'magenta_stained_glass_pane' },
    { 'name': 'Magenta Terracotta', 'item': 'magenta_terracotta' },
    { 'name': 'Magenta Wall Banner', 'item': 'magenta_wall_banner' },
    { 'name': 'Magenta Wool', 'item': 'magenta_wool' },
    { 'name': 'Magma Block', 'item': 'magma_block' },
    { 'name': 'Melon', 'item': 'melon' },
    { 'name': 'Melon Stem', 'item': 'melon_stem' },
    { 'name': 'Mossy Cobblestone', 'item': 'mossy_cobblestone' },
    { 'name': 'Mossy Cobblestone Slab', 'item': 'mossy_cobblestone_slab' },
    { 'name': 'Mossy Cobblestone Stairs', 'item': 'mossy_cobblestone_stairs' },
    { 'name': 'Mossy Cobblestone Wall', 'item': 'mossy_cobblestone_wall' },
    { 'name': 'Mossy Stone Brick Slab', 'item': 'mossy_stone_brick_slab' },
    { 'name': 'Mossy Stone Brick Stairs', 'item': 'mossy_stone_brick_stairs' },
    { 'name': 'Mossy Stone Brick Wall', 'item': 'mossy_stone_brick_wall' },
    { 'name': 'Mossy Stone Bricks', 'item': 'mossy_stone_bricks' },
    { 'name': 'Moving Piston', 'item': 'moving_piston' },
    { 'name': 'Mushroom Stem', 'item': 'mushroom_stem' },
    { 'name': 'Mycelium', 'item': 'mycelium' },
    { 'name': 'Nether Brick Fence', 'item': 'nether_brick_fence' },
    { 'name': 'Nether Brick Slab', 'item': 'nether_brick_slab' },
    { 'name': 'Nether Brick Stairs', 'item': 'nether_brick_stairs' },
    { 'name': 'Nether Brick Wall', 'item': 'nether_brick_wall' },
    { 'name': 'Nether Bricks', 'item': 'nether_bricks' },
    { 'name': 'Nether Portal', 'item': 'nether_portal' },
    { 'name': 'Nether Quartz Ore', 'item': 'nether_quartz_ore' },
    { 'name': 'Nether Wart Block', 'item': 'nether_wart_block' },
    { 'name': 'Nether Wart', 'item': 'nether_wart' },
    { 'name': 'Netherrack', 'item': 'netherrack' },
    { 'name': 'Note Block', 'item': 'note_block' },
    { 'name': 'Oak Button', 'item': 'oak_button' },
    { 'name': 'Oak Door', 'item': 'oak_door' },
    { 'name': 'Oak Fence Gate', 'item': 'oak_fence_gate' },
    { 'name': 'Oak Fence', 'item': 'oak_fence' },
    { 'name': 'Oak Leaves', 'item': 'oak_leaves' },
    { 'name': 'Oak Log', 'item': 'oak_log' },
    { 'name': 'Oak Planks', 'item': 'oak_planks' },
    { 'name': 'Oak Pressure Plate', 'item': 'oak_pressure_plate' },
    { 'name': 'Oak Sapling', 'item': 'oak_sapling' },
    { 'name': 'Oak Sign', 'item': 'oak_sign' },
    { 'name': 'Oak Slab', 'item': 'oak_slab' },
    { 'name': 'Oak Stairs', 'item': 'oak_stairs' },
    { 'name': 'Oak Trapdoor', 'item': 'oak_trapdoor' },
    { 'name': 'Oak Wall Sign', 'item': 'oak_wall_sign' },
    { 'name': 'Oak Wood', 'item': 'oak_wood' },
    { 'name': 'Observer', 'item': 'observer' },
    { 'name': 'Obsidian', 'item': 'obsidian' },
    { 'name': 'Orange Banner', 'item': 'orange_banner' },
    { 'name': 'Orange Bed', 'item': 'orange_bed' },
    { 'name': 'Orange Carpet', 'item': 'orange_carpet' },
    { 'name': 'Orange Concrete Powder', 'item': 'orange_concrete_powder' },
    { 'name': 'Orange Concrete', 'item': 'orange_concrete' },
    { 'name': 'Orange Glazed Terracotta', 'item': 'orange_glazed_terracotta' },
    { 'name': 'Orange Shulker Box', 'item': 'orange_shulker_box' },
    { 'name': 'Orange Stained Glass', 'item': 'orange_stained_glass' },
    { 'name': 'Orange Stained Glass Pane', 'item': 'orange_stained_glass_pane' },
    { 'name': 'Orange Terracotta', 'item': 'orange_terracotta' },
    { 'name': 'Orange Tulip', 'item': 'orange_tulip' },
    { 'name': 'Orange Wall Banner', 'item': 'orange_wall_banner' },
    { 'name': 'Orange Wool', 'item': 'orange_wool' },
    { 'name': 'Oxeye Daisy', 'item': 'oxeye_daisy' },
    { 'name': 'Packed Ice', 'item': 'packed_ice' },
    { 'name': 'Peony', 'item': 'peony' },
    { 'name': 'Petrified Oak Slab', 'item': 'petrified_oak_slab' },
    { 'name': 'Pink Banner', 'item': 'pink_banner' },
    { 'name': 'Pink Bed', 'item': 'pink_bed' },
    { 'name': 'Pink Carpet', 'item': 'pink_carpet' },
    { 'name': 'Pink Concrete Powder', 'item': 'pink_concrete_powder' },
    { 'name': 'Pink Concrete', 'item': 'pink_concrete' },
    { 'name': 'Pink Glazed Terracotta', 'item': 'pink_glazed_terracotta' },
    { 'name': 'Pink Shulker Box', 'item': 'pink_shulker_box' },
    { 'name': 'Pink Stained Glass', 'item': 'pink_stained_glass' },
    { 'name': 'Pink Stained Glass Pane', 'item': 'pink_stained_glass_pane' },
    { 'name': 'Pink Terracotta', 'item': 'pink_terracotta' },
    { 'name': 'Pink Tulip', 'item': 'pink_tulip' },
    { 'name': 'Pink Wall Banner', 'item': 'pink_wall_banner' },
    { 'name': 'Pink Wool', 'item': 'pink_wool' },
    { 'name': 'Piston Head', 'item': 'piston_head' },
    { 'name': 'Piston', 'item': 'piston' },
    { 'name': 'Player Head', 'item': 'player_head' },
    { 'name': 'Player Wall Head', 'item': 'player_wall_head' },
    { 'name': 'Podzol', 'item': 'podzol' },
    { 'name': 'Polished Andesite', 'item': 'polished_andesite' },
    { 'name': 'Polished Andesite Slab', 'item': 'polished_andesite_slab' },
    { 'name': 'Polished Andesite Stairs', 'item': 'polished_andesite_stairs' },
    { 'name': 'Polished Diorite', 'item': 'polished_diorite' },
    { 'name': 'Polished Diorite Slab', 'item': 'polished_diorite_slab' },
    { 'name': 'Polished Diorite Stairs', 'item': 'polished_diorite_stairs' },
    { 'name': 'Polished Granite', 'item': 'polished_granite' },
    { 'name': 'Polished Granite Slab', 'item': 'polished_granite_slab' },
    { 'name': 'Polished Granite Stairs', 'item': 'polished_granite_stairs' },
    { 'name': 'Poppy', 'item': 'poppy' },
    { 'name': 'Potatoes', 'item': 'potatoes' },
    { 'name': 'Potted Acacia Sapling', 'item': 'potted_acacia_sapling' },
    { 'name': 'Potted Allium', 'item': 'potted_allium' },
    { 'name': 'Potted Azure Bluet', 'item': 'potted_azure_bluet' },
    { 'name': 'Potted Bamboo', 'item': 'potted_bamboo' },
    { 'name': 'Potted Birch Sapling', 'item': 'potted_birch_sapling' },
    { 'name': 'Potted Blue Orchid', 'item': 'potted_blue_orchid' },
    { 'name': 'Potted Brown Mushroom', 'item': 'potted_brown_mushroom' },
    { 'name': 'Potted Cactus', 'item': 'potted_cactus' },
    { 'name': 'Potted Cornflower', 'item': 'potted_cornflower' },
    { 'name': 'Potted Dandelion', 'item': 'potted_dandelion' },
    { 'name': 'Potted Dark Oak Sapling', 'item': 'potted_dark_oak_sapling' },
    { 'name': 'Potted Dead Bush', 'item': 'potted_dead_bush' },
    { 'name': 'Potted Fern', 'item': 'potted_fern' },
    { 'name': 'Potted Jungle Sapling', 'item': 'potted_jungle_sapling' },
    { 'name': 'Potted Lily of the Valley', 'item': 'potted_lily_of_the_valley' },
    { 'name': 'Potted Oak Sapling', 'item': 'potted_oak_sapling' },
    { 'name': 'Potted Orange Tulip', 'item': 'potted_orange_tulip' },
    { 'name': 'Potted Oxeye Daisy', 'item': 'potted_oxeye_daisy' },
    { 'name': 'Potted Pink Tulip', 'item': 'potted_pink_tulip' },
    { 'name': 'Potted Poppy', 'item': 'potted_poppy' },
    { 'name': 'Potted Red Mushroom', 'item': 'potted_red_mushroom' },
    { 'name': 'Potted Red Tulip', 'item': 'potted_red_tulip' },
    { 'name': 'Potted Spruce Sapling', 'item': 'potted_spruce_sapling' },
    { 'name': 'Potted White Tulip', 'item': 'potted_white_tulip' },
    { 'name': 'Potted Wither Rose', 'item': 'potted_wither_rose' },
    { 'name': 'Powered Rail', 'item': 'powered_rail' },
    { 'name': 'Prismarine', 'item': 'prismarine' },
    { 'name': 'Prismarine Brick Slab', 'item': 'prismarine_brick_slab' },
    { 'name': 'Prismarine Brick Stairs', 'item': 'prismarine_brick_stairs' },
    { 'name': 'Prismarine Bricks', 'item': 'prismarine_bricks' },
    { 'name': 'Prismarine Slab', 'item': 'prismarine_slab' },
    { 'name': 'Prismarine Stairs', 'item': 'prismarine_stairs' },
    { 'name': 'Prismarine Wall', 'item': 'prismarine_wall' },
    { 'name': 'Pumpkin', 'item': 'pumpkin' },
    { 'name': 'Pumpkin Stem', 'item': 'pumpkin_stem' },
    { 'name': 'Purple Banner', 'item': 'purple_banner' },
    { 'name': 'Purple Bed', 'item': 'purple_bed' },
    { 'name': 'Purple Carpet', 'item': 'purple_carpet' },
    { 'name': 'Purple Concrete Powder', 'item': 'purple_concrete_powder' },
    { 'name': 'Purple Concrete', 'item': 'purple_concrete' },
    { 'name': 'Purple Glazed Terracotta', 'item': 'purple_glazed_terracotta' },
    { 'name': 'Purple Shulker Box', 'item': 'purple_shulker_box' },
    { 'name': 'Purple Stained Glass', 'item': 'purple_stained_glass' },
    { 'name': 'Purple Stained Glass Pane', 'item': 'purple_stained_glass_pane' },
    { 'name': 'Purple Terracotta', 'item': 'purple_terracotta' },
    { 'name': 'Purple Wall Banner', 'item': 'purple_wall_banner' },
    { 'name': 'Purple Wool', 'item': 'purple_wool' },
    { 'name': 'Purpur Block', 'item': 'purpur_block' },
    { 'name': 'Purpur Pillar', 'item': 'purpur_pillar' },
    { 'name': 'Purpur Slab', 'item': 'purpur_slab' },
    { 'name': 'Purpur Stairs', 'item': 'purpur_stairs' },
    { 'name': 'Block of Quartz', 'item': 'quartz_block' },
    { 'name': 'Quartz Pillar', 'item': 'quartz_pillar' },
    { 'name': 'Quartz Slab', 'item': 'quartz_slab' },
    { 'name': 'Quartz Stairs', 'item': 'quartz_stairs' },
    { 'name': 'Rail', 'item': 'rail' },
    { 'name': 'Red Banner', 'item': 'red_banner' },
    { 'name': 'Red Bed', 'item': 'red_bed' },
    { 'name': 'Red Carpet', 'item': 'red_carpet' },
    { 'name': 'Red Concrete Powder', 'item': 'red_concrete_powder' },
    { 'name': 'Red Concrete', 'item': 'red_concrete' },
    { 'name': 'Red Glazed Terracotta', 'item': 'red_glazed_terracotta' },
    { 'name': 'Red Mushroom Block', 'item': 'red_mushroom_block' },
    { 'name': 'Red Mushroom', 'item': 'red_mushroom' },
    { 'name': 'Red Nether Brick Slab', 'item': 'red_nether_brick_slab' },
    { 'name': 'Red Nether Brick Stairs', 'item': 'red_nether_brick_stairs' },
    { 'name': 'Red Nether Brick Wall', 'item': 'red_nether_brick_wall' },
    { 'name': 'Red Nether Bricks', 'item': 'red_nether_bricks' },
    { 'name': 'Red Sand', 'item': 'red_sand' },
    { 'name': 'Red Sandstone', 'item': 'red_sandstone' },
    { 'name': 'Red Sandstone Slab', 'item': 'red_sandstone_slab' },
    { 'name': 'Red Sandstone Stairs', 'item': 'red_sandstone_stairs' },
    { 'name': 'Red Sandstone Wall', 'item': 'red_sandstone_wall' },
    { 'name': 'Red Shulker Box', 'item': 'red_shulker_box' },
    { 'name': 'Red Stained Glass', 'item': 'red_stained_glass' },
    { 'name': 'Red Stained Glass Pane', 'item': 'red_stained_glass_pane' },
    { 'name': 'Red Terracotta', 'item': 'red_terracotta' },
    { 'name': 'Red Tulip', 'item': 'red_tulip' },
    { 'name': 'Red Wall Banner', 'item': 'red_wall_banner' },
    { 'name': 'Red Wool', 'item': 'red_wool' },
    { 'name': 'Block of Redstone', 'item': 'redstone_block' },
    { 'name': 'Redstone Lamp', 'item': 'redstone_lamp' },
    { 'name': 'Redstone Ore', 'item': 'redstone_ore' },
    { 'name': 'Redstone Torch', 'item': 'redstone_torch' },
    { 'name': 'Redstone Wall Torch', 'item': 'redstone_wall_torch' },
    { 'name': 'Redstone Dust', 'item': 'redstone_wire' },
    { 'name': 'Redstone Repeater', 'item': 'repeater' },
    { 'name': 'Repeating Command Block', 'item': 'repeating_command_block' },
    { 'name': 'Rose Bush', 'item': 'rose_bush' },
    { 'name': 'Sand', 'item': 'sand' },
    { 'name': 'Sandstone', 'item': 'sandstone' },
    { 'name': 'Sandstone Slab', 'item': 'sandstone_slab' },
    { 'name': 'Sandstone Stairs', 'item': 'sandstone_stairs' },
    { 'name': 'Sandstone Wall', 'item': 'sandstone_wall' },
    { 'name': 'Scaffolding', 'item': 'scaffolding' },
    { 'name': 'Sea Lantern', 'item': 'sea_lantern' },
    { 'name': 'Sea Pickle', 'item': 'sea_pickle' },
    { 'name': 'Seagrass', 'item': 'seagrass' },
    { 'name': 'Shulker Box', 'item': 'shulker_box' },
    { 'name': 'Skeleton Skull', 'item': 'skeleton_skull' },
    { 'name': 'Skeleton Wall Skull', 'item': 'skeleton_wall_skull' },
    { 'name': 'Slime Block', 'item': 'slime_block' },
    { 'name': 'Smithing Table', 'item': 'smithing_table' },
    { 'name': 'Smoker', 'item': 'smoker' },
    { 'name': 'Smooth Quartz', 'item': 'smooth_quartz' },
    { 'name': 'Smooth Quartz Slab', 'item': 'smooth_quartz_slab' },
    { 'name': 'Smooth Quartz Stairs', 'item': 'smooth_quartz_stairs' },
    { 'name': 'Smooth Red Sandstone', 'item': 'smooth_red_sandstone' },
    { 'name': 'Smooth Red Sandstone Slab', 'item': 'smooth_red_sandstone_slab' },
    { 'name': 'Smooth Red Sandstone Stairs', 'item': 'smooth_red_sandstone_stairs' },
    { 'name': 'Smooth Sandstone', 'item': 'smooth_sandstone' },
    { 'name': 'Smooth Sandstone Slab', 'item': 'smooth_sandstone_slab' },
    { 'name': 'Smooth Sandstone Stairs', 'item': 'smooth_sandstone_stairs' },
    { 'name': 'Smooth Stone', 'item': 'smooth_stone' },
    { 'name': 'Smooth Stone Slab', 'item': 'smooth_stone_slab' },
    { 'name': 'Snow Block', 'item': 'snow_block' },
    { 'name': 'Snow', 'item': 'snow' },
    { 'name': 'Soul Sand', 'item': 'soul_sand' },
    { 'name': 'Spawner', 'item': 'spawner' },
    { 'name': 'Sponge', 'item': 'sponge' },
    { 'name': 'Spruce Button', 'item': 'spruce_button' },
    { 'name': 'Spruce Door', 'item': 'spruce_door' },
    { 'name': 'Spruce Fence Gate', 'item': 'spruce_fence_gate' },
    { 'name': 'Spruce Fence', 'item': 'spruce_fence' },
    { 'name': 'Spruce Leaves', 'item': 'spruce_leaves' },
    { 'name': 'Spruce Log', 'item': 'spruce_log' },
    { 'name': 'Spruce Planks', 'item': 'spruce_planks' },
    { 'name': 'Spruce Pressure Plate', 'item': 'spruce_pressure_plate' },
    { 'name': 'Spruce Sapling', 'item': 'spruce_sapling' },
    { 'name': 'Spruce Sign', 'item': 'spruce_sign' },
    { 'name': 'Spruce Slab', 'item': 'spruce_slab' },
    { 'name': 'Spruce Stairs', 'item': 'spruce_stairs' },
    { 'name': 'Spruce Trapdoor', 'item': 'spruce_trapdoor' },
    { 'name': 'Spruce Wall Sign', 'item': 'spruce_wall_sign' },
    { 'name': 'Spruce Wood', 'item': 'spruce_wood' },
    { 'name': 'Sticky Piston', 'item': 'sticky_piston' },
    { 'name': 'Stone', 'item': 'stone' },
    { 'name': 'Stone Brick Slab', 'item': 'stone_brick_slab' },
    { 'name': 'Stone Brick Stairs', 'item': 'stone_brick_stairs' },
    { 'name': 'Stone Brick Wall', 'item': 'stone_brick_wall' },
    { 'name': 'Stone Bricks', 'item': 'stone_bricks' },
    { 'name': 'Stone Button', 'item': 'stone_button' },
    { 'name': 'Stone Pressure Plate', 'item': 'stone_pressure_plate' },
    { 'name': 'Stone Slab', 'item': 'stone_slab' },
    { 'name': 'Stone Stairs', 'item': 'stone_stairs' },
    { 'name': 'Stonecutter', 'item': 'stonecutter' },
    { 'name': 'Stripped Acacia Log', 'item': 'stripped_acacia_log' },
    { 'name': 'Stripped Acacia Wood', 'item': 'stripped_acacia_wood' },
    { 'name': 'Stripped Birch Log', 'item': 'stripped_birch_log' },
    { 'name': 'Stripped Birch Wood', 'item': 'stripped_birch_wood' },
    { 'name': 'Stripped Dark Oak Log', 'item': 'stripped_dark_oak_log' },
    { 'name': 'Stripped Dark Oak Wood', 'item': 'stripped_dark_oak_wood' },
    { 'name': 'Stripped Jungle Log', 'item': 'stripped_jungle_log' },
    { 'name': 'Stripped Jungle Wood', 'item': 'stripped_jungle_wood' },
    { 'name': 'Stripped Oak Log', 'item': 'stripped_oak_log' },
    { 'name': 'Stripped Oak Wood', 'item': 'stripped_oak_wood' },
    { 'name': 'Stripped Spruce Log', 'item': 'stripped_spruce_log' },
    { 'name': 'Stripped Spruce Wood', 'item': 'stripped_spruce_wood' },
    { 'name': 'Structure Block', 'item': 'structure_block' },
    { 'name': 'Structure Void', 'item': 'structure_void' },
    { 'name': 'Sugar Cane', 'item': 'sugar_cane' },
    { 'name': 'Sunflower', 'item': 'sunflower' },
    { 'name': 'Sweet Berry Bush', 'item': 'sweet_berry_bush' },
    { 'name': 'TNT', 'item': 'tnt' },
    { 'name': 'Tall Grass', 'item': 'tall_grass' },
    { 'name': 'Tall Seagrass', 'item': 'tall_seagrass' },
    { 'name': 'Terracotta', 'item': 'terracotta' },
    { 'name': 'Torch', 'item': 'torch' },
    { 'name': 'Trapped Chest', 'item': 'trapped_chest' },
    { 'name': 'Tripwire Hook', 'item': 'tripwire_hook' },
    { 'name': 'Tripwire', 'item': 'tripwire' },
    { 'name': 'Tube Coral', 'item': 'tube_coral' },
    { 'name': 'Tube Coral Block', 'item': 'tube_coral_block' },
    { 'name': 'Tube Coral Fan', 'item': 'tube_coral_fan' },
    { 'name': 'Tube Coral Wall Fan', 'item': 'tube_coral_wall_fan' },
    { 'name': 'Turtle Egg', 'item': 'turtle_egg' },
    { 'name': 'Vines', 'item': 'vine' },
    { 'name': 'Void Air', 'item': 'void_air' },
    { 'name': 'Wall Torch', 'item': 'wall_torch' },
    { 'name': 'Water', 'item': 'water' },
    { 'name': 'Wet Sponge', 'item': 'wet_sponge' },
    { 'name': 'Wheat', 'item': 'wheat' },
    { 'name': 'White Banner', 'item': 'white_banner' },
    { 'name': 'White Bed', 'item': 'white_bed' },
    { 'name': 'White Carpet', 'item': 'white_carpet' },
    { 'name': 'White Concrete Powder', 'item': 'white_concrete_powder' },
    { 'name': 'White Concrete', 'item': 'white_concrete' },
    { 'name': 'White Glazed Terracotta', 'item': 'white_glazed_terracotta' },
    { 'name': 'White Shulker Box', 'item': 'white_shulker_box' },
    { 'name': 'White Stained Glass', 'item': 'white_stained_glass' },
    { 'name': 'White Stained Glass Pane', 'item': 'white_stained_glass_pane' },
    { 'name': 'White Terracotta', 'item': 'white_terracotta' },
    { 'name': 'White Tulip', 'item': 'white_tulip' },
    { 'name': 'White Wall Banner', 'item': 'white_wall_banner' },
    { 'name': 'White Wool', 'item': 'white_wool' },
    { 'name': 'Wither Rose', 'item': 'wither_rose' },
    { 'name': 'Wither Skeleton Skull', 'item': 'wither_skeleton_skull' },
    { 'name': 'Wither Skeleton Wall Skull', 'item': 'wither_skeleton_wall_skull' },
    { 'name': 'Yellow Banner', 'item': 'yellow_banner' },
    { 'name': 'Yellow Bed', 'item': 'yellow_bed' },
    { 'name': 'Yellow Carpet', 'item': 'yellow_carpet' },
    { 'name': 'Yellow Concrete Powder', 'item': 'yellow_concrete_powder' },
    { 'name': 'Yellow Concrete', 'item': 'yellow_concrete' },
    { 'name': 'Yellow Glazed Terracotta', 'item': 'yellow_glazed_terracotta' },
    { 'name': 'Yellow Shulker Box', 'item': 'yellow_shulker_box' },
    { 'name': 'Yellow Stained Glass', 'item': 'yellow_stained_glass' },
    { 'name': 'Yellow Stained Glass Pane', 'item': 'yellow_stained_glass_pane' },
    { 'name': 'Yellow Terracotta', 'item': 'yellow_terracotta' },
    { 'name': 'Yellow Wall Banner', 'item': 'yellow_wall_banner' },
    { 'name': 'Yellow Wool', 'item': 'yellow_wool' },
    { 'name': 'Zombie Head', 'item': 'zombie_head' },
    { 'name': 'Zombie Wall Head', 'item': 'zombie_wall_head' },
    { 'name': 'Acacia Boat', 'item': 'acacia_boat' },
    { 'name': 'Apple', 'item': 'apple' },
    { 'name': 'Armor Stand', 'item': 'armor_stand' },
    { 'name': 'Arrow', 'item': 'arrow' },
    { 'name': 'Baked Potato', 'item': 'baked_potato' },
    { 'name': 'Bat Spawn Egg', 'item': 'bat_spawn_egg' },
    { 'name': 'Raw Beef', 'item': 'beef' },
    { 'name': 'Beetroot Seeds', 'item': 'beetroot_seeds' },
    { 'name': 'Beetroot Soup', 'item': 'beetroot_soup' },
    { 'name': 'Beetroot', 'item': 'beetroot' },
    { 'name': 'Birch Boat', 'item': 'birch_boat' },
    { 'name': 'Black Dye', 'item': 'black_dye' },
    { 'name': 'Blaze Powder', 'item': 'blaze_powder' },
    { 'name': 'Blaze Rod', 'item': 'blaze_rod' },
    { 'name': 'Blaze Spawn Egg', 'item': 'blaze_spawn_egg' },
    { 'name': 'Blue Dye', 'item': 'blue_dye' },
    { 'name': 'Bone Meal', 'item': 'bone_meal' },
    { 'name': 'Bone', 'item': 'bone' },
    { 'name': 'Book', 'item': 'book' },
    { 'name': 'Book and Quill', 'item': 'writable_book' },
    { 'name': "Bottle o' Enchanting", 'item': 'experience_bottle' },
    { 'name': 'Bowl', 'item': 'bowl' },
    { 'name': 'Bow', 'item': 'bow' },
    { 'name': 'Bread', 'item': 'bread' },
    { 'name': 'Brick', 'item': 'brick' },
    { 'name': 'Brown Dye', 'item': 'brown_dye' },
    { 'name': 'Bucket', 'item': 'bucket' },
    { 'name': 'Green Dye', 'item': 'green_dye' },
    { 'name': 'Carrot on a Stick', 'item': 'carrot_on_a_stick' },
    { 'name': 'Carrot', 'item': 'carrot' },
    { 'name': 'Cat Spawn Egg', 'item': 'cat_spawn_egg' },
    { 'name': 'Cave Spider Spawn Egg', 'item': 'cave_spider_spawn_egg' },
    { 'name': 'Chainmail Boots', 'item': 'chainmail_boots' },
    { 'name': 'Chainmail Chestplate', 'item': 'chainmail_chestplate' },
    { 'name': 'Chainmail Helmet', 'item': 'chainmail_helmet' },
    { 'name': 'Chainmail Leggings', 'item': 'chainmail_leggings' },
    { 'name': 'Charcoal', 'item': 'charcoal' },
    { 'name': 'Minecart with Chest', 'item': 'chest_minecart' },
    { 'name': 'Raw Chicken', 'item': 'chicken' },
    { 'name': 'Chicken Spawn Egg', 'item': 'chicken_spawn_egg' },
    { 'name': 'Chorus Fruit', 'item': 'chorus_fruit' },
    { 'name': 'Clay', 'item': 'clay_ball' },
    { 'name': 'Clock', 'item': 'clock' },
    { 'name': 'Coal', 'item': 'coal' },
    { 'name': 'Cocoa Beans', 'item': 'cocoa_beans' },
    { 'name': 'Raw Cod', 'item': 'cod' },
    { 'name': 'Bucket of Cod', 'item': 'cod_bucket' },
    { 'name': 'Cod Spawn Egg', 'item': 'cod_spawn_egg' },
    { 'name': 'Minecart with Command Block', 'item': 'command_block_minecart' },
    { 'name': 'Compass', 'item': 'compass' },
    { 'name': 'Cooked Chicken', 'item': 'cooked_chicken' },
    { 'name': 'Cooked Cod', 'item': 'cooked_cod' },
    { 'name': 'Cooked Mutton', 'item': 'cooked_mutton' },
    { 'name': 'Cooked Porkchop', 'item': 'cooked_porkchop' },
    { 'name': 'Cooked Rabbit', 'item': 'cooked_rabbit' },
    { 'name': 'Cooked Salmon', 'item': 'cooked_salmon' },
    { 'name': 'Cookie', 'item': 'cookie' },
    { 'name': 'Cow Spawn Egg', 'item': 'cow_spawn_egg' },
    { 'name': 'Creeper Spawn Egg', 'item': 'creeper_spawn_egg' },
    { 'name': 'Crossbow', 'item': 'crossbow' },
    { 'name': 'Cyan Dye', 'item': 'cyan_dye' },
    { 'name': 'Dark Oak Boat', 'item': 'dark_oak_boat' },
    { 'name': 'Debug Stick', 'item': 'debug_stick' },
    { 'name': 'Diamond Axe', 'item': 'diamond_axe' },
    { 'name': 'Diamond Boots', 'item': 'diamond_boots' },
    { 'name': 'Diamond Chestplate', 'item': 'diamond_chestplate' },
    { 'name': 'Diamond Helmet', 'item': 'diamond_helmet' },
    { 'name': 'Diamond Hoe', 'item': 'diamond_hoe' },
    { 'name': 'Diamond Horse Armor', 'item': 'diamond_horse_armor' },
    { 'name': 'Diamond Leggings', 'item': 'diamond_leggings' },
    { 'name': 'Diamond Pickaxe', 'item': 'diamond_pickaxe' },
    { 'name': 'Diamond Shovel', 'item': 'diamond_shovel' },
    { 'name': 'Diamond Sword', 'item': 'diamond_sword' },
    { 'name': 'Diamond', 'item': 'diamond' },
    { 'name': 'Dolphin Spawn Egg', 'item': 'dolphin_spawn_egg' },
    { 'name': 'Donkey Spawn Egg', 'item': 'donkey_spawn_egg' },
    { 'name': "Dragon's Breath", 'item': 'dragon_breath' },
    { 'name': 'Dried Kelp', 'item': 'dried_kelp' },
    { 'name': 'Drowned Spawn Egg', 'item': 'drowned_spawn_egg' },
    { 'name': 'Egg', 'item': 'egg' },
    { 'name': 'Elder Guardian Spawn Egg', 'item': 'elder_guardian_spawn_egg' },
    { 'name': 'Elytra', 'item': 'elytra' },
    { 'name': 'Emerald', 'item': 'emerald' },
    { 'name': 'Empty Map', 'item': 'map' },
    { 'name': 'Enchanted Book', 'item': 'enchanted_book' },
    { 'name': 'Enchanted Golden Apple', 'item': 'enchanted_golden_apple' },
    { 'name': 'End Crystal', 'item': 'end_crystal' },
    { 'name': 'Eye of Ender', 'item': 'ender_eye' },
    { 'name': 'Ender Pearl', 'item': 'ender_pearl' },
    { 'name': 'Enderman Spawn Egg', 'item': 'enderman_spawn_egg' },
    { 'name': 'Endermite Spawn Egg', 'item': 'endermite_spawn_egg' },
    { 'name': 'Evoker Spawn Egg', 'item': 'evoker_spawn_egg' },
    { 'name': 'Feather', 'item': 'feather' },
    { 'name': 'Fermented Spider Eye', 'item': 'fermented_spider_eye' },
    { 'name': 'Fire Charge', 'item': 'fire_charge' },
    { 'name': 'Firework Rocket', 'item': 'firework_rocket' },
    { 'name': 'Firework Star', 'item': 'firework_star' },
    { 'name': 'Fishing Rod', 'item': 'fishing_rod' },
    { 'name': 'Flint', 'item': 'flint' },
    { 'name': 'Flint and Steel', 'item': 'flint_and_steel' },
    { 'name': 'Banner Pattern (Flower Charge)', 'item': 'flower_banner_pattern' },
    { 'name': 'Fox Spawn Egg', 'item': 'fox_spawn_egg' },
    { 'name': 'Minecart with Furnace', 'item': 'furnace_minecart' },
    { 'name': 'Ghast Spawn Egg', 'item': 'ghast_spawn_egg' },
    { 'name': 'Ghast Tear', 'item': 'ghast_tear' },
    { 'name': 'Glass Bottle', 'item': 'glass_bottle' },
    { 'name': 'Glistering Melon Slice', 'item': 'glistering_melon_slice' },
    { 'name': 'Banner Pattern (Globe)', 'item': 'globe_banner_pattern' },
    { 'name': 'Glowstone Dust', 'item': 'glowstone_dust' },
    { 'name': 'Gold Ingot', 'item': 'gold_ingot' },
    { 'name': 'Gold Nugget', 'item': 'gold_nugget' },
    { 'name': 'Golden Apple', 'item': 'golden_apple' },
    { 'name': 'Golden Axe', 'item': 'golden_axe' },
    { 'name': 'Golden Boots', 'item': 'golden_boots' },
    { 'name': 'Golden Carrot', 'item': 'golden_carrot' },
    { 'name': 'Golden Chestplate', 'item': 'golden_chestplate' },
    { 'name': 'Golden Helmet', 'item': 'golden_helmet' },
    { 'name': 'Golden Hoe', 'item': 'golden_hoe' },
    { 'name': 'Golden Horse Armor', 'item': 'golden_horse_armor' },
    { 'name': 'Golden Leggings', 'item': 'golden_leggings' },
    { 'name': 'Golden Pickaxe', 'item': 'golden_pickaxe' },
    { 'name': 'Golden Shovel', 'item': 'golden_shovel' },
    { 'name': 'Golden Sword', 'item': 'golden_sword' },
    { 'name': 'Gray Dye', 'item': 'gray_dye' },
    { 'name': 'Guardian Spawn Egg', 'item': 'guardian_spawn_egg' },
    { 'name': 'Gunpowder', 'item': 'gunpowder' },
    { 'name': 'Heart of the Sea', 'item': 'heart_of_the_sea' },
    { 'name': 'Minecart with Hopper', 'item': 'hopper_minecart' },
    { 'name': 'Horse Spawn Egg', 'item': 'horse_spawn_egg' },
    { 'name': 'Husk Spawn Egg', 'item': 'husk_spawn_egg' },
    { 'name': 'Ink Sac', 'item': 'ink_sac' },
    { 'name': 'Iron Axe', 'item': 'iron_axe' },
    { 'name': 'Iron Boots', 'item': 'iron_boots' },
    { 'name': 'Iron Chestplate', 'item': 'iron_chestplate' },
    { 'name': 'Iron Helmet', 'item': 'iron_helmet' },
    { 'name': 'Iron Hoe', 'item': 'iron_hoe' },
    { 'name': 'Iron Horse Armor', 'item': 'iron_horse_armor' },
    { 'name': 'Iron Ingot', 'item': 'iron_ingot' },
    { 'name': 'Iron Leggings', 'item': 'iron_leggings' },
    { 'name': 'Iron Nugget', 'item': 'iron_nugget' },
    { 'name': 'Iron Pickaxe', 'item': 'iron_pickaxe' },
    { 'name': 'Iron Shovel', 'item': 'iron_shovel' },
    { 'name': 'Iron Sword', 'item': 'iron_sword' },
    { 'name': 'Item Frame', 'item': 'item_frame' },
    { 'name': 'Jungle Boat', 'item': 'jungle_boat' },
    { 'name': 'Knowledge Book', 'item': 'knowledge_book' },
    { 'name': 'Lapis Lazuli', 'item': 'lapis_lazuli' },
    { 'name': 'Lava Bucket', 'item': 'lava_bucket' },
    { 'name': 'Lead', 'item': 'lead' },
    { 'name': 'Leather', 'item': 'leather' },
    { 'name': 'Leather Boots', 'item': 'leather_boots' },
    { 'name': 'Leather Cap', 'item': 'leather_helmet' },
    { 'name': 'Leather Horse Armor', 'item': 'leather_horse_armor' },
    { 'name': 'Leather Pants', 'item': 'leather_leggings' },
    { 'name': 'Leather Tunic', 'item': 'leather_chestplate' },
    { 'name': 'Light Blue Dye', 'item': 'light_blue_dye' },
    { 'name': 'Light Gray Dye', 'item': 'light_gray_dye' },
    { 'name': 'Lime Dye', 'item': 'lime_dye' },
    { 'name': 'Lingering Potions', 'item': 'lingering_potion' },
    { 'name': 'Llama Spawn Egg', 'item': 'llama_spawn_egg' },
    { 'name': 'Magenta Dye', 'item': 'magenta_dye' },
    { 'name': 'Magma Cream', 'item': 'magma_cream' },
    { 'name': 'Magma Cube Spawn Egg', 'item': 'magma_cube_spawn_egg' },
    { 'name': 'Map or Explorer Map', 'item': 'filled_map' },
    { 'name': 'Melon Seeds', 'item': 'melon_seeds' },
    { 'name': 'Melon Slice', 'item': 'melon_slice' },
    { 'name': 'Milk Bucket', 'item': 'milk_bucket' },
    { 'name': 'Minecart', 'item': 'minecart' },
    { 'name': 'Banner Pattern (Thing)', 'item': 'mojang_banner_pattern' },
    { 'name': 'Mooshroom Spawn Egg', 'item': 'mooshroom_spawn_egg' },
    { 'name': 'Mule Spawn Egg', 'item': 'mule_spawn_egg' },
    { 'name': 'Mushroom Stew', 'item': 'mushroom_stew' },
    { 'name': 'Music Disc (11)', 'item': 'music_disc_11' },
    { 'name': 'Music Disc (13)', 'item': 'music_disc_13' },
    { 'name': 'Music Disc (Blocks)', 'item': 'music_disc_blocks' },
    { 'name': 'Music Disc (Cat)', 'item': 'music_disc_cat' },
    { 'name': 'Music Disc (Chirp)', 'item': 'music_disc_chirp' },
    { 'name': 'Music Disc (Far)', 'item': 'music_disc_far' },
    { 'name': 'Music Disc (Mall)', 'item': 'music_disc_mall' },
    { 'name': 'Music Disc (Mellohi)', 'item': 'music_disc_mellohi' },
    { 'name': 'Music Disc (Stal)', 'item': 'music_disc_stal' },
    { 'name': 'Music Disc (Strad)', 'item': 'music_disc_strad' },
    { 'name': 'Music Disc (Wait)', 'item': 'music_disc_wait' },
    { 'name': 'Music Disc (Ward)', 'item': 'music_disc_ward' },
    { 'name': 'Raw Mutton', 'item': 'mutton' },
    { 'name': 'Name Tag', 'item': 'name_tag' },
    { 'name': 'Nautilus Shell', 'item': 'nautilus_shell' },
    { 'name': 'Nether Brick', 'item': 'nether_brick' },
    { 'name': 'Nether Quartz', 'item': 'quartz' },
    { 'name': 'Nether Star', 'item': 'nether_star' },
    { 'name': 'Oak Boat', 'item': 'oak_boat' },
    { 'name': 'Ocelot Spawn Egg', 'item': 'ocelot_spawn_egg' },
    { 'name': 'Orange Dye', 'item': 'orange_dye' },
    { 'name': 'Painting', 'item': 'painting' },
    { 'name': 'Panda Spawn Egg', 'item': 'panda_spawn_egg' },
    { 'name': 'Paper', 'item': 'paper' },
    { 'name': 'Parrot Spawn Egg', 'item': 'parrot_spawn_egg' },
    { 'name': 'Phantom Membrane', 'item': 'phantom_membrane' },
    { 'name': 'Phantom Spawn Egg', 'item': 'phantom_spawn_egg' },
    { 'name': 'Pig Spawn Egg', 'item': 'pig_spawn_egg' },
    { 'name': 'Pillager Spawn Egg', 'item': 'pillager_spawn_egg' },
    { 'name': 'Pink Dye', 'item': 'pink_dye' },
    { 'name': 'Poisonous Potato', 'item': 'poisonous_potato' },
    { 'name': 'Polar Bear Spawn Egg', 'item': 'polar_bear_spawn_egg' },
    { 'name': 'Popped Chorus Fruit', 'item': 'popped_chorus_fruit' },
    { 'name': 'Raw Porkchop', 'item': 'porkchop' },
    { 'name': 'Potato', 'item': 'potato' },
    { 'name': 'Potions', 'item': 'potion' },
    { 'name': 'Prismarine Crystals', 'item': 'prismarine_crystals' },
    { 'name': 'Prismarine Shard', 'item': 'prismarine_shard' },
    { 'name': 'Pufferfish', 'item': 'pufferfish' },
    { 'name': 'Bucket of Pufferfish', 'item': 'pufferfish_bucket' },
    { 'name': 'Pufferfish Spawn Egg', 'item': 'pufferfish_spawn_egg' },
    { 'name': 'Pumpkin Pie', 'item': 'pumpkin_pie' },
    { 'name': 'Pumpkin Seeds', 'item': 'pumpkin_seeds' },
    { 'name': 'Purple Dye', 'item': 'purple_dye' },
    { 'name': 'Raw Rabbit', 'item': 'rabbit' },
    { 'name': "Rabbit's Foot", 'item': 'rabbit_foot' },
    { 'name': 'Rabbit Hide', 'item': 'rabbit_hide' },
    { 'name': 'Rabbit Spawn Egg', 'item': 'rabbit_spawn_egg' },
    { 'name': 'Rabbit Stew', 'item': 'rabbit_stew' },
    { 'name': 'Ravager Spawn Egg', 'item': 'ravager_spawn_egg' },
    { 'name': 'Redstone Dust', 'item': 'redstone' },
    { 'name': 'Red Dye', 'item': 'red_dye' },
    { 'name': 'Rotten Flesh', 'item': 'rotten_flesh' },
    { 'name': 'Saddle', 'item': 'saddle' },
    { 'name': 'Raw Salmon', 'item': 'salmon' },
    { 'name': 'Bucket of Salmon', 'item': 'salmon_bucket' },
    { 'name': 'Salmon Spawn Egg', 'item': 'salmon_spawn_egg' },
    { 'name': 'Scute', 'item': 'scute' },
    { 'name': 'Shears', 'item': 'shears' },
    { 'name': 'Sheep Spawn Egg', 'item': 'sheep_spawn_egg' },
    { 'name': 'Shield', 'item': 'shield' },
    { 'name': 'Shulker Shell', 'item': 'shulker_shell' },
    { 'name': 'Shulker Spawn Egg', 'item': 'shulker_spawn_egg' },
    { 'name': 'Silverfish Spawn Egg', 'item': 'silverfish_spawn_egg' },
    { 'name': 'Skeleton Horse Spawn Egg', 'item': 'skeleton_horse_spawn_egg' },
    { 'name': 'Skeleton Spawn Egg', 'item': 'skeleton_spawn_egg' },
    { 'name': 'Banner Pattern (Skull Charge)', 'item': 'skull_banner_pattern' },
    { 'name': 'Slime Spawn Egg', 'item': 'slime_spawn_egg' },
    { 'name': 'Slimeball', 'item': 'slime_ball' },
    { 'name': 'Snowball', 'item': 'snowball' },
    { 'name': 'Spectral Arrow', 'item': 'spectral_arrow' },
    { 'name': 'Spider Eye', 'item': 'spider_eye' },
    { 'name': 'Spider Spawn Egg', 'item': 'spider_spawn_egg' },
    { 'name': 'Splash Potions', 'item': 'splash_potion' },
    { 'name': 'Spruce Boat', 'item': 'spruce_boat' },
    { 'name': 'Squid Spawn Egg', 'item': 'squid_spawn_egg' },
    { 'name': 'Steak', 'item': 'cooked_beef' },
    { 'name': 'Stick', 'item': 'stick' },
    { 'name': 'Stone Axe', 'item': 'stone_axe' },
    { 'name': 'Stone Hoe', 'item': 'stone_hoe' },
    { 'name': 'Stone Pickaxe', 'item': 'stone_pickaxe' },
    { 'name': 'Stone Shovel', 'item': 'stone_shovel' },
    { 'name': 'Stone Sword', 'item': 'stone_sword' },
    { 'name': 'Stray Spawn Egg', 'item': 'stray_spawn_egg' },
    { 'name': 'String', 'item': 'string' },
    { 'name': 'Sugar', 'item': 'sugar' },
    { 'name': 'Suspicious Stew', 'item': 'suspicious_stew' },
    { 'name': 'Sweet Berries', 'item': 'sweet_berries' },
    { 'name': 'Tipped Arrows', 'item': 'tipped_arrow' },
    { 'name': 'Minecart with TNT', 'item': 'tnt_minecart' },
    { 'name': 'Totem of Undying', 'item': 'totem_of_undying' },
    { 'name': 'Trader Llama Spawn Egg', 'item': 'trader_llama_spawn_egg' },
    { 'name': 'Trident', 'item': 'trident' },
    { 'name': 'Tropical Fish', 'item': 'tropical_fish' },
    { 'name': 'Bucket of Tropical Fish', 'item': 'tropical_fish_bucket' },
    { 'name': 'Tropical Fish Spawn Egg', 'item': 'tropical_fish_spawn_egg' },
    { 'name': 'Turtle Shell', 'item': 'turtle_helmet' },
    { 'name': 'Turtle Spawn Egg', 'item': 'turtle_spawn_egg' },
    { 'name': 'Vex Spawn Egg', 'item': 'vex_spawn_egg' },
    { 'name': 'Villager Spawn Egg', 'item': 'villager_spawn_egg' },
    { 'name': 'Vindicator Spawn Egg', 'item': 'vindicator_spawn_egg' },
    { 'name': 'Water Bucket', 'item': 'water_bucket' },
    { 'name': 'Wheat Seeds', 'item': 'wheat_seeds' },
    { 'name': 'White Dye', 'item': 'white_dye' },
    { 'name': 'Witch Spawn Egg', 'item': 'witch_spawn_egg' },
    { 'name': 'Wither Skeleton Spawn Egg', 'item': 'wither_skeleton_spawn_egg' },
    { 'name': 'Wolf Spawn Egg', 'item': 'wolf_spawn_egg' },
    { 'name': 'Wooden Axe', 'item': 'wooden_axe' },
    { 'name': 'Wooden Hoe', 'item': 'wooden_hoe' },
    { 'name': 'Wooden Pickaxe', 'item': 'wooden_pickaxe' },
    { 'name': 'Wooden Shovel', 'item': 'wooden_shovel' },
    { 'name': 'Wooden Sword', 'item': 'wooden_sword' },
    { 'name': 'Written Book', 'item': 'written_book' },
    { 'name': 'Yellow Dye', 'item': 'yellow_dye' },
    { 'name': 'Zombie Horse Spawn Egg', 'item': 'zombie_horse_spawn_egg' },
    { 'name': 'Zombie Pigman Spawn Egg', 'item': 'zombie_pigman_spawn_egg' },
    { 'name': 'Zombie Spawn Egg', 'item': 'zombie_spawn_egg' },
    { 'name': 'Zombie Villager Spawn Egg', 'item': 'zombie_villager_spawn_egg' }
  ]
}
