/*
  Name: Data-Module (AllData.js)
  Description: Contains static data for the server.
  Author: Janis Jendraß
  ForVersion: <1.14.X
 */
module.exports = function AllData () {
  this.items = [
    { name: 'Acacia Button', item: 'Acacia_Button' },
    { name: 'Acacia Door', item: 'Acacia_Door' },
    { name: 'Acacia Fence', item: 'Acacia_Fence' },
    { name: 'Acacia Fence Gate', item: 'Acacia_Fence_Gate' },
    { name: 'Acacia Leaves', item: 'Acacia_Leaves' },
    { name: 'Acacia Log', item: 'Acacia_Log' },
    { name: 'Acacia Planks', item: 'Acacia_Planks' },
    { name: 'Acacia Pressure Plate', item: 'Acacia_Pressure_Plate' },
    { name: 'Acacia Sapling', item: 'Acacia_Sapling' },
    { name: 'Acacia Sign', item: 'Acacia_Sign' },
    { name: 'Acacia Slab', item: 'Acacia_Slab' },
    { name: 'Acacia Stairs', item: 'Acacia_Stairs' },
    { name: 'Acacia Trapdoor', item: 'Acacia_Trapdoor' },
    { name: 'Acacia Wood', item: 'Acacia_Wood' },
    { name: 'Activator Rail', item: 'Activator_Rail' },
    { name: 'Allium', item: 'Allium' },
    { name: 'Amethyst Cluster', item: 'Amethyst_Cluster' },
    { name: 'Ancient Debris', item: 'Ancient_Debris' },
    { name: 'Andesite', item: 'Andesite' },
    { name: 'Andesite Slab', item: 'Andesite_Slab' },
    { name: 'Andesite Stairs', item: 'Andesite_Stairs' },
    { name: 'Andesite Wall', item: 'Andesite_Wall' },
    { name: 'Anvil', item: 'Anvil' },
    { name: 'Azalea', item: 'Azalea' },
    { name: 'Azalea Leaves', item: 'Azalea_Leaves' },
    { name: 'Azure Bluet', item: 'Azure_Bluet' },
    { name: 'Bamboo', item: 'Bamboo' },
    { name: 'Bamboo Shoot', item: 'Bamboo_Shoot' },
    { name: 'Barrel', item: 'Barrel' },
    { name: 'Barrier', item: 'Barrier' },
    { name: 'Basalt', item: 'Basalt' },
    { name: 'Beacon', item: 'Beacon' },
    { name: 'Bedrock', item: 'Bedrock' },
    { name: 'Bee Nest', item: 'Bee_Nest' },
    { name: 'Beehive', item: 'Beehive' },
    { name: 'Beetroots', item: 'Beetroots' },
    { name: 'Bell', item: 'Bell' },
    { name: 'Big Dripleaf', item: 'Big_Dripleaf' },
    { name: 'Birch Button', item: 'Birch_Button' },
    { name: 'Birch Door', item: 'Birch_Door' },
    { name: 'Birch Fence', item: 'Birch_Fence' },
    { name: 'Birch Fence Gate', item: 'Birch_Fence_Gate' },
    { name: 'Birch Leaves', item: 'Birch_Leaves' },
    { name: 'Birch Log', item: 'Birch_Log' },
    { name: 'Birch Planks', item: 'Birch_Planks' },
    { name: 'Birch Pressure Plate', item: 'Birch_Pressure_Plate' },
    { name: 'Birch Sapling', item: 'Birch_Sapling' },
    { name: 'Birch Sign', item: 'Birch_Sign' },
    { name: 'Birch Slab', item: 'Birch_Slab' },
    { name: 'Birch Stairs', item: 'Birch_Stairs' },
    { name: 'Birch Trapdoor', item: 'Birch_Trapdoor' },
    { name: 'Birch Wood', item: 'Birch_Wood' },
    { name: 'Black Banner', item: 'Black_Banner' },
    { name: 'Black Bed', item: 'Black_Bed' },
    { name: 'Black Candle', item: 'Black_Candle' },
    { name: 'Black Carpet', item: 'Black_Carpet' },
    { name: 'Black Concrete', item: 'Black_Concrete' },
    { name: 'Black Concrete Powder', item: 'Black_Concrete_Powder' },
    { name: 'Black Glazed Terracotta', item: 'Black_Glazed_Terracotta' },
    { name: 'Black Shulker Box', item: 'Black_Shulker_Box' },
    { name: 'Black Stained Glass', item: 'Black_Stained_Glass' },
    { name: 'Black Stained Glass Pane', item: 'Black_Stained_Glass_Pane' },
    { name: 'Black Terracotta', item: 'Black_Terracotta' },
    { name: 'Black Wool', item: 'Black_Wool' },
    { name: 'Blackstone', item: 'Blackstone' },
    { name: 'Blackstone Slab', item: 'Blackstone_Slab' },
    { name: 'Blackstone Stairs', item: 'Blackstone_Stairs' },
    { name: 'Blackstone Wall', item: 'Blackstone_Wall' },
    { name: 'Blast Furnace', item: 'Blast_Furnace' },
    { name: 'Block of Amethyst', item: 'Block_of_Amethyst' },
    { name: 'Block of Coal', item: 'Block_of_Coal' },
    { name: 'Block of Copper', item: 'Block_of_Copper' },
    { name: 'Block of Diamond', item: 'Block_of_Diamond' },
    { name: 'Block of Emerald', item: 'Block_of_Emerald' },
    { name: 'Block of Gold', item: 'Block_of_Gold' },
    { name: 'Block of Iron', item: 'Block_of_Iron' },
    { name: 'Block of Lapis Lazuli', item: 'Block_of_Lapis_Lazuli' },
    { name: 'Block of Netherite', item: 'Block_of_Netherite' },
    { name: 'Block of Quartz', item: 'Block_of_Quartz' },
    { name: 'Block of Raw Copper', item: 'Block_of_Raw_Copper' },
    { name: 'Block of Raw Gold', item: 'Block_of_Raw_Gold' },
    { name: 'Block of Raw Iron', item: 'Block_of_Raw_Iron' },
    { name: 'Block of Redstone', item: 'Block_of_Redstone' },
    { name: 'Blue Banner', item: 'Blue_Banner' },
    { name: 'Blue Bed', item: 'Blue_Bed' },
    { name: 'Blue Candle', item: 'Blue_Candle' },
    { name: 'Blue Carpet', item: 'Blue_Carpet' },
    { name: 'Blue Concrete', item: 'Blue_Concrete' },
    { name: 'Blue Concrete Powder', item: 'Blue_Concrete_Powder' },
    { name: 'Blue Glazed Terracotta', item: 'Blue_Glazed_Terracotta' },
    { name: 'Blue Ice', item: 'Blue_Ice' },
    { name: 'Blue Orchid', item: 'Blue_Orchid' },
    { name: 'Blue Shulker Box', item: 'Blue_Shulker_Box' },
    { name: 'Blue Stained Glass', item: 'Blue_Stained_Glass' },
    { name: 'Blue Stained Glass Pane', item: 'Blue_Stained_Glass_Pane' },
    { name: 'Blue Terracotta', item: 'Blue_Terracotta' },
    { name: 'Blue Wool', item: 'Blue_Wool' },
    { name: 'Bone Block', item: 'Bone_Block' },
    { name: 'Bookshelf', item: 'Bookshelf' },
    { name: 'Brain Coral', item: 'Brain_Coral' },
    { name: 'Brain Coral Block', item: 'Brain_Coral_Block' },
    { name: 'Brain Coral Fan', item: 'Brain_Coral_Fan' },
    { name: 'Brewing Stand', item: 'Brewing_Stand' },
    { name: 'Brick Slab', item: 'Brick_Slab' },
    { name: 'Brick Stairs', item: 'Brick_Stairs' },
    { name: 'Brick Wall', item: 'Brick_Wall' },
    { name: 'Bricks', item: 'Bricks' },
    { name: 'Brown Banner', item: 'Brown_Banner' },
    { name: 'Brown Bed', item: 'Brown_Bed' },
    { name: 'Brown Candle', item: 'Brown_Candle' },
    { name: 'Brown Carpet', item: 'Brown_Carpet' },
    { name: 'Brown Concrete', item: 'Brown_Concrete' },
    { name: 'Brown Concrete Powder', item: 'Brown_Concrete_Powder' },
    { name: 'Brown Glazed Terracotta', item: 'Brown_Glazed_Terracotta' },
    { name: 'Brown Mushroom', item: 'Brown_Mushroom' },
    { name: 'Brown Mushroom Block', item: 'Brown_Mushroom_Block' },
    { name: 'Brown Shulker Box', item: 'Brown_Shulker_Box' },
    { name: 'Brown Stained Glass', item: 'Brown_Stained_Glass' },
    { name: 'Brown Stained Glass Pane', item: 'Brown_Stained_Glass_Pane' },
    { name: 'Brown Terracotta', item: 'Brown_Terracotta' },
    { name: 'Brown Wool', item: 'Brown_Wool' },
    { name: 'Bubble Coral', item: 'Bubble_Coral' },
    { name: 'Bubble Coral Block', item: 'Bubble_Coral_Block' },
    { name: 'Bubble Coral Fan', item: 'Bubble_Coral_Fan' },
    { name: 'Budding Amethyst', item: 'Budding_Amethyst' },
    { name: 'Cactus', item: 'Cactus' },
    { name: 'Cake', item: 'Cake' },
    { name: 'Calcite', item: 'Calcite' },
    { name: 'Campfire', item: 'Campfire' },
    { name: 'Candle', item: 'Candle' },
    { name: 'Carrots', item: 'Carrot' },
    { name: 'Cartography Table', item: 'Cartography_Table' },
    { name: 'Carved Pumpkin', item: 'Carved_Pumpkin' },
    { name: 'Cauldron', item: 'Cauldron' },
    { name: 'Cave Vines', item: 'Cave_Vines' },
    { name: 'Chain', item: 'Chain' },
    { name: 'Chain Command Block', item: 'Chain_Command_Block' },
    { name: 'Chest', item: 'Chest' },
    { name: 'Chipped Anvil', item: 'Chipped_Anvil' },
    { name: 'Chiseled Deepslate', item: 'Chiseled_Deepslate' },
    { name: 'Chiseled Nether Bricks', item: 'Chiseled_Nether_Bricks' },
    { name: 'Chiseled Polished Blackstone', item: 'Chiseled_Polished_Blackstone' },
    { name: 'Chiseled Quartz Block', item: 'Chiseled_Quartz_Block' },
    { name: 'Chiseled Red Sandstone', item: 'Chiseled_Red_Sandstone' },
    { name: 'Chiseled Sandstone', item: 'Chiseled_Sandstone' },
    { name: 'Chiseled Stone Bricks', item: 'Chiseled_Stone_Bricks' },
    { name: 'Chorus Flower', item: 'Chorus_Flower' },
    { name: 'Chorus Plant', item: 'Chorus_Plant' },
    { name: 'Clay', item: 'Clay' },
    { name: 'Coal Ore', item: 'Coal_Ore' },
    { name: 'Coarse Dirt', item: 'Coarse_Dirt' },
    { name: 'Cobbled Deepslate', item: 'Cobbled_Deepslate' },
    { name: 'Cobbled Deepslate Slab', item: 'Cobbled_Deepslate_Slab' },
    { name: 'Cobbled Deepslate Stairs', item: 'Cobbled_Deepslate_Stairs' },
    { name: 'Cobbled Deepslate Wall', item: 'Cobbled_Deepslate_Wall' },
    { name: 'Cobblestone', item: 'Cobblestone' },
    { name: 'Cobblestone Slab', item: 'Cobblestone_Slab' },
    { name: 'Cobblestone Stairs', item: 'Cobblestone_Stairs' },
    { name: 'Cobblestone Wall', item: 'Cobblestone_Wall' },
    { name: 'Cobweb', item: 'Cobweb' },
    { name: 'Cocoa', item: 'Cocoa' },
    { name: 'Command Block', item: 'Command_Block' },
    { name: 'Composter', item: 'Composter' },
    { name: 'Conduit', item: 'Conduit' },
    { name: 'Copper Ore', item: 'Copper_Ore' },
    { name: 'Cornflower', item: 'Cornflower' },
    { name: 'Cracked Deepslate Bricks', item: 'Cracked_Deepslate_Bricks' },
    { name: 'Cracked Deepslate Tiles', item: 'Cracked_Deepslate_Tiles' },
    { name: 'Cracked Nether Bricks', item: 'Cracked_Nether_Bricks' },
    { name: 'Cracked Polished Blackstone Bricks', item: 'Cracked_Polished_Blackstone_Bricks' },
    { name: 'Cracked Stone Bricks', item: 'Cracked_Stone_Bricks' },
    { name: 'Crafting Table', item: 'Crafting_Table' },
    { name: 'Creeper Head', item: 'Creeper_Head' },
    { name: 'Crimson Button', item: 'Crimson_Button' },
    { name: 'Crimson Door', item: 'Crimson_Door' },
    { name: 'Crimson Fence', item: 'Crimson_Fence' },
    { name: 'Crimson Fence Gate', item: 'Crimson_Fence_Gate' },
    { name: 'Crimson Fungus', item: 'Crimson_Fungus' },
    { name: 'Crimson Hyphae', item: 'Crimson_Hyphae' },
    { name: 'Crimson Nylium', item: 'Crimson_Nylium' },
    { name: 'Crimson Planks', item: 'Crimson_Planks' },
    { name: 'Crimson Pressure Plate', item: 'Crimson_Pressure_Plate' },
    { name: 'Crimson Roots', item: 'Crimson_Roots' },
    { name: 'Crimson Sign', item: 'Crimson_Sign' },
    { name: 'Crimson Slab', item: 'Crimson_Slab' },
    { name: 'Crimson Stairs', item: 'Crimson_Stairs' },
    { name: 'Crimson Stem', item: 'Crimson_Stem' },
    { name: 'Crimson Trapdoor', item: 'Crimson_Trapdoor' },
    { name: 'Crying Obsidian', item: 'Crying_Obsidian' },
    { name: 'Cut Copper', item: 'Cut_Copper' },
    { name: 'Cut Copper Slab', item: 'Cut_Copper_Slab' },
    { name: 'Cut Copper Stairs', item: 'Cut_Copper_Stairs' },
    { name: 'Cut Red Sandstone', item: 'Cut_Red_Sandstone' },
    { name: 'Cut Red Sandstone Slab', item: 'Cut_Red_Sandstone_Slab' },
    { name: 'Cut Sandstone', item: 'Cut_Sandstone' },
    { name: 'Cut Sandstone Slab', item: 'Cut_Sandstone_Slab' },
    { name: 'Cyan Banner', item: 'Cyan_Banner' },
    { name: 'Cyan Bed', item: 'Cyan_Bed' },
    { name: 'Cyan Candle', item: 'Cyan_Candle' },
    { name: 'Cyan Carpet', item: 'Cyan_Carpet' },
    { name: 'Cyan Concrete', item: 'Cyan_Concrete' },
    { name: 'Cyan Concrete Powder', item: 'Cyan_Concrete_Powder' },
    { name: 'Cyan Glazed Terracotta', item: 'Cyan_Glazed_Terracotta' },
    { name: 'Cyan Shulker Box', item: 'Cyan_Shulker_Box' },
    { name: 'Cyan Stained Glass', item: 'Cyan_Stained_Glass' },
    { name: 'Cyan Stained Glass Pane', item: 'Cyan_Stained_Glass_Pane' },
    { name: 'Cyan Terracotta', item: 'Cyan_Terracotta' },
    { name: 'Cyan Wool', item: 'Cyan_Wool' },
    { name: 'Damaged Anvil', item: 'Damaged_Anvil' },
    { name: 'Dandelion', item: 'Dandelion' },
    { name: 'Dark Oak Button', item: 'Dark_Oak_Button' },
    { name: 'Dark Oak Door', item: 'Dark_Oak_Door' },
    { name: 'Dark Oak Fence', item: 'Dark_Oak_Fence' },
    { name: 'Dark Oak Fence Gate', item: 'Dark_Oak_Fence_Gate' },
    { name: 'Dark Oak Leaves', item: 'Dark_Oak_Leaves' },
    { name: 'Dark Oak Log', item: 'Dark_Oak_Log' },
    { name: 'Dark Oak Planks', item: 'Dark_Oak_Planks' },
    { name: 'Dark Oak Pressure Plate', item: 'Dark_Oak_Pressure_Plate' },
    { name: 'Dark Oak Sapling', item: 'Dark_Oak_Sapling' },
    { name: 'Dark Oak Sign', item: 'Dark_Oak_Sign' },
    { name: 'Dark Oak Slab', item: 'Dark_Oak_Slab' },
    { name: 'Dark Oak Stairs', item: 'Dark_Oak_Stairs' },
    { name: 'Dark Oak Trapdoor', item: 'Dark_Oak_Trapdoor' },
    { name: 'Dark Oak Wood', item: 'Dark_Oak_Wood' },
    { name: 'Dark Prismarine', item: 'Dark_Prismarine' },
    { name: 'Dark Prismarine Slab', item: 'Dark_Prismarine_Slab' },
    { name: 'Dark Prismarine Stairs', item: 'Dark_Prismarine_Stairs' },
    { name: 'Daylight Detector', item: 'Daylight_Detector' },
    { name: 'Dead Brain Coral', item: 'Dead_Brain_Coral' },
    { name: 'Dead Brain Coral Block', item: 'Dead_Brain_Coral_Block' },
    { name: 'Dead Brain Coral Fan', item: 'Dead_Brain_Coral_Fan' },
    { name: 'Dead Bubble Coral', item: 'Dead_Bubble_Coral' },
    { name: 'Dead Bubble Coral Block', item: 'Dead_Bubble_Coral_Block' },
    { name: 'Dead Bubble Coral Fan', item: 'Dead_Bubble_Coral_Fan' },
    { name: 'Dead Bush', item: 'Dead_Bush' },
    { name: 'Dead Fire Coral', item: 'Dead_Fire_Coral' },
    { name: 'Dead Fire Coral Block', item: 'Dead_Fire_Coral_Block' },
    { name: 'Dead Fire Coral Fan', item: 'Dead_Fire_Coral_Fan' },
    { name: 'Dead Horn Coral', item: 'Dead_Horn_Coral' },
    { name: 'Dead Horn Coral Block', item: 'Dead_Horn_Coral_Block' },
    { name: 'Dead Horn Coral Fan', item: 'Dead_Horn_Coral_Fan' },
    { name: 'Dead Tube Coral', item: 'Dead_Tube_Coral' },
    { name: 'Dead Tube Coral Block', item: 'Dead_Tube_Coral_Block' },
    { name: 'Dead Tube Coral Fan', item: 'Dead_Tube_Coral_Fan' },
    { name: 'Deepslate', item: 'Deepslate' },
    { name: 'Deepslate Bricks', item: 'Deepslate_Bricks' },
    { name: 'Deepslate Brick Slab', item: 'Deepslate_Brick_Slab' },
    { name: 'Deepslate Brick Stairs', item: 'Deepslate_Brick_Stairs' },
    { name: 'Deepslate Brick Wall', item: 'Deepslate_Brick_Wall' },
    { name: 'Deepslate Coal Ore', item: 'Deepslate_Coal_Ore' },
    { name: 'Deepslate Copper Ore', item: 'Deepslate_Copper_Ore' },
    { name: 'Deepslate Diamond Ore', item: 'Deepslate_Diamond_Ore' },
    { name: 'Deepslate Emerald Ore', item: 'Deepslate_Emerald_Ore' },
    { name: 'Deepslate Gold Ore', item: 'Deepslate_Gold_Ore' },
    { name: 'Deepslate Iron Ore', item: 'Deepslate_Iron_Ore' },
    { name: 'Deepslate Lapis Lazuli Ore', item: 'Deepslate_Lapis_Lazuli_Ore' },
    { name: 'Deepslate Redstone Ore', item: 'Deepslate_Redstone_Ore' },
    { name: 'Deepslate Tiles', item: 'Deepslate_Tiles' },
    { name: 'Deepslate Tile Slab', item: 'Deepslate_Tile_Slab' },
    { name: 'Deepslate Tile Stairs', item: 'Deepslate_Tile_Stairs' },
    { name: 'Deepslate Tile Wall', item: 'Deepslate_Tile_Wall' },
    { name: 'Detector Rail', item: 'Detector_Rail' },
    { name: 'Diamond Ore', item: 'Diamond_Ore' },
    { name: 'Diorite', item: 'Diorite' },
    { name: 'Diorite Slab', item: 'Diorite_Slab' },
    { name: 'Diorite Stairs', item: 'Diorite_Stairs' },
    { name: 'Diorite Wall', item: 'Diorite_Wall' },
    { name: 'Dirt', item: 'Dirt' },
    { name: 'Dirt Path', item: 'Dirt_Path' },
    { name: 'Dispenser', item: 'Dispenser' },
    { name: 'Dragon Egg', item: 'Dragon_Egg' },
    { name: 'Dragon Head', item: 'Dragon_Head' },
    { name: 'Dried Kelp Block', item: 'Dried_Kelp_Block' },
    { name: 'Dripstone Block', item: 'Dripstone_Block' },
    { name: 'Dropper', item: 'Dropper' },
    { name: 'Emerald Ore', item: 'Emerald_Ore' },
    { name: 'Enchanting Table', item: 'Enchanting_Table' },
    { name: 'End Portal Frame', item: 'End_Portal_Frame' },
    { name: 'End Rod', item: 'End_Rod' },
    { name: 'End Stone', item: 'End_Stone' },
    { name: 'End Stone Brick Slab', item: 'End_Stone_Brick_Slab' },
    { name: 'End Stone Brick Stairs', item: 'End_Stone_Brick_Stairs' },
    { name: 'End Stone Brick Wall', item: 'End_Stone_Brick_Wall' },
    { name: 'End Stone Bricks', item: 'End_Stone_Bricks' },
    { name: 'Ender Chest', item: 'Ender_Chest' },
    { name: 'Exposed Copper', item: 'Exposed_Copper' },
    { name: 'Exposed Cut Copper', item: 'Exposed_Cut_Copper' },
    { name: 'Exposed Cut Copper Slab', item: 'Exposed_Cut_Copper_Slab' },
    { name: 'Exposed Cut Copper Stairs', item: 'Exposed_Cut_Copper_Stairs' },
    { name: 'Farmland', item: 'Farmland' },
    { name: 'Fern', item: 'Fern' },
    { name: 'Fire', item: 'Fire' },
    { name: 'Fire Coral', item: 'Fire_Coral' },
    { name: 'Fire Coral Block', item: 'Fire_Coral_Block' },
    { name: 'Fire Coral Fan', item: 'Fire_Coral_Fan' },
    { name: 'Fletching Table', item: 'Fletching_Table' },
    { name: 'Flower Pot', item: 'Flower_Pot' },
    { name: 'Flowering Azalea', item: 'Flowering_Azalea' },
    { name: 'Flowering Azalea Leaves', item: 'Flowering_Azalea_Leaves' },
    { name: 'Frogspawn', item: 'Frogspawn' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Furnace', item: 'Furnace' },
    { name: 'Gilded Blackstone', item: 'Gilded_Blackstone' },
    { name: 'Glass', item: 'Glass' },
    { name: 'Glass Pane', item: 'Glass_Pane' },
    { name: 'Glow Item Frame', item: 'Glow_Item_Frame' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Glow Lichen', item: 'Glow_Lichen' },
    { name: 'Glowing Obsidian', item: 'Glowing_Obsidian' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Glowstone', item: 'Glowstone' },
    { name: 'Gold Ore', item: 'Gold_Ore' },
    { name: 'Granite', item: 'Granite' },
    { name: 'Granite Slab', item: 'Granite_Slab' },
    { name: 'Granite Stairs', item: 'Granite_Stairs' },
    { name: 'Granite Wall', item: 'Granite_Wall' },
    { name: 'Grass', item: 'Grass' },
    { name: 'Grass Block', item: 'Grass_Block' },
    { name: 'Gravel', item: 'Gravel' },
    { name: 'Gray Banner', item: 'Gray_Banner' },
    { name: 'Gray Bed', item: 'Gray_Bed' },
    { name: 'Gray Candle', item: 'Gray_Candle' },
    { name: 'Gray Carpet', item: 'Gray_Carpet' },
    { name: 'Gray Concrete', item: 'Gray_Concrete' },
    { name: 'Gray Concrete Powder', item: 'Gray_Concrete_Powder' },
    { name: 'Gray Glazed Terracotta', item: 'Gray_Glazed_Terracotta' },
    { name: 'Gray Shulker Box', item: 'Gray_Shulker_Box' },
    { name: 'Gray Stained Glass', item: 'Gray_Stained_Glass' },
    { name: 'Gray Stained Glass Pane', item: 'Gray_Stained_Glass_Pane' },
    { name: 'Gray Terracotta', item: 'Gray_Terracotta' },
    { name: 'Gray Wool', item: 'Gray_Wool' },
    { name: 'Green Banner', item: 'Green_Banner' },
    { name: 'Green Bed', item: 'Green_Bed' },
    { name: 'Green Candle', item: 'Green_Candle' },
    { name: 'Green Carpet', item: 'Green_Carpet' },
    { name: 'Green Concrete', item: 'Green_Concrete' },
    { name: 'Green Concrete Powder', item: 'Green_Concrete_Powder' },
    { name: 'Green Glazed Terracotta', item: 'Green_Glazed_Terracotta' },
    { name: 'Green Shulker Box', item: 'Green_Shulker_Box' },
    { name: 'Green Stained Glass', item: 'Green_Stained_Glass' },
    { name: 'Green Stained Glass Pane', item: 'Green_Stained_Glass_Pane' },
    { name: 'Green Terracotta', item: 'Green_Terracotta' },
    { name: 'Green Wool', item: 'Green_Wool' },
    { name: 'Grindstone', item: 'Grindstone' },
    { name: 'Hanging Roots', item: 'Hanging_Roots' },
    { name: 'Hay Bale', item: 'Hay_Bale' },
    { name: 'Heavy Weighted Pressure Plate', item: 'Heavy_Weighted_Pressure_Plate' },
    { name: 'Honey Block', item: 'Honey_Block' },
    { name: 'Honeycomb Block', item: 'Honeycomb_Block' },
    { name: 'Hopper', item: 'Hopper' },
    { name: 'Horn Coral', item: 'Horn_Coral' },
    { name: 'Horn Coral Block', item: 'Horn_Coral_Block' },
    { name: 'Horn Coral Fan', item: 'Horn_Coral_Fan' },
    { name: 'Ice', item: 'Ice' },
    { name: 'Infested Chiseled Stone Bricks', item: 'Infested_Chiseled_Stone_Bricks' },
    { name: 'Infested Cobblestone', item: 'Infested_Cobblestone' },
    { name: 'Infested Cracked Stone Bricks', item: 'Infested_Cracked_Stone_Bricks' },
    { name: 'Infested Deepslate', item: 'Infested_Deepslate' },
    { name: 'Infested Mossy Stone Bricks', item: 'Infested_Mossy_Stone_Bricks' },
    { name: 'Infested Stone', item: 'Infested_Stone' },
    { name: 'Infested Stone Bricks', item: 'Infested_Stone_Bricks' },
    { name: 'Iron Bars', item: 'Iron_Bars' },
    { name: 'Iron Door', item: 'Iron_Door' },
    { name: 'Iron Ore', item: 'Iron_Ore' },
    { name: 'Iron Trapdoor', item: 'Iron_Trapdoor' },
    { name: 'Item Frame', item: 'Item_Frame' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Jack o Lantern', item: 'Jack_o_Lantern' },
    { name: 'Jigsaw Block', item: 'Jigsaw_Block' },
    { name: 'Jukebox', item: 'Jukebox' },
    { name: 'Jungle Button', item: 'Jungle_Button' },
    { name: 'Jungle Door', item: 'Jungle_Door' },
    { name: 'Jungle Fence', item: 'Jungle_Fence' },
    { name: 'Jungle Fence Gate', item: 'Jungle_Fence_Gate' },
    { name: 'Jungle Leaves', item: 'Jungle_Leaves' },
    { name: 'Jungle Log', item: 'Jungle_Log' },
    { name: 'Jungle Planks', item: 'Jungle_Planks' },
    { name: 'Jungle Pressure Plate', item: 'Jungle_Pressure_Plate' },
    { name: 'Jungle Sapling', item: 'Jungle_Sapling' },
    { name: 'Jungle Sign', item: 'Jungle_Sign' },
    { name: 'Jungle Slab', item: 'Jungle_Slab' },
    { name: 'Jungle Stairs', item: 'Jungle_Stairs' },
    { name: 'Jungle Trapdoor', item: 'Jungle_Trapdoor' },
    { name: 'Jungle Wood', item: 'Jungle_Wood' },
    { name: 'Kelp', item: 'Kelp' },
    { name: 'Ladder', item: 'Ladder' },
    { name: 'Lantern', item: 'Lantern' },
    { name: 'Lapis Lazuli Ore', item: 'Lapis_Lazuli_Ore' },
    { name: 'Large Amethyst Bud', item: 'Large_Amethyst_Bud' },
    { name: 'Large Fern', item: 'Large_Fern' },
    { name: 'Lava', item: 'Lava' },
    { name: 'Lectern', item: 'Lectern' },
    { name: 'Lever', item: 'Lever' },
    { name: 'Light Block', item: 'Light_Block' },
    { name: 'Light Blue Banner', item: 'Light_Blue_Banner' },
    { name: 'Light Blue Bed', item: 'Light_Blue_Bed' },
    { name: 'Light Blue Candle', item: 'Light_Blue_Candle' },
    { name: 'Light Blue Carpet', item: 'Light_Blue_Carpet' },
    { name: 'Light Blue Concrete', item: 'Light_Blue_Concrete' },
    { name: 'Light Blue Concrete Powder', item: 'Light_Blue_Concrete_Powder' },
    { name: 'Light Blue Glazed Terracotta', item: 'Light_Blue_Glazed_Terracotta' },
    { name: 'Light Blue Shulker Box', item: 'Light_Blue_Shulker_Box' },
    { name: 'Light Blue Stained Glass', item: 'Light_Blue_Stained_Glass' },
    { name: 'Light Blue Stained Glass Pane', item: 'Light_Blue_Stained_Glass_Pane' },
    { name: 'Light Blue Terracotta', item: 'Light_Blue_Terracotta' },
    { name: 'Light Blue Wool', item: 'Light_Blue_Wool' },
    { name: 'Light Gray Banner', item: 'Light_Gray_Banner' },
    { name: 'Light Gray Bed', item: 'Light_Gray_Bed' },
    { name: 'Light Gray Candle', item: 'Light_Gray_Candle' },
    { name: 'Light Gray Carpet', item: 'Light_Gray_Carpet' },
    { name: 'Light Gray Concrete', item: 'Light_Gray_Concrete' },
    { name: 'Light Gray Concrete Powder', item: 'Light_Gray_Concrete_Powder' },
    { name: 'Light Gray Glazed Terracotta', item: 'Light_Gray_Glazed_Terracotta' },
    { name: 'Light Gray Shulker Box', item: 'Light_Gray_Shulker_Box' },
    { name: 'Light Gray Stained Glass', item: 'Light_Gray_Stained_Glass' },
    { name: 'Light Gray Stained Glass Pane', item: 'Light_Gray_Stained_Glass_Pane' },
    { name: 'Light Gray Terracotta', item: 'Light_Gray_Terracotta' },
    { name: 'Light Gray Wool', item: 'Light_Gray_Wool' },
    { name: 'Light Weighted Pressure Plate', item: 'Light_Weighted_Pressure_Plate' },
    { name: 'Lightning Rod', item: 'Lightning_Rod' },
    { name: 'Lilac', item: 'Lilac' },
    { name: 'Lily of the Valley', item: 'Lily_of_the_Valley' },
    { name: 'Lily Pad', item: 'Lily_Pad' },
    { name: 'Lime Banner', item: 'Lime_Banner' },
    { name: 'Lime Bed', item: 'Lime_Bed' },
    { name: 'Lime Candle', item: 'Lime_Candle' },
    { name: 'Lime Carpet', item: 'Lime_Carpet' },
    { name: 'Lime Concrete', item: 'Lime_Concrete' },
    { name: 'Lime Concrete Powder', item: 'Lime_Concrete_Powder' },
    { name: 'Lime Glazed Terracotta', item: 'Lime_Glazed_Terracotta' },
    { name: 'Lime Shulker Box', item: 'Lime_Shulker_Box' },
    { name: 'Lime Stained Glass', item: 'Lime_Stained_Glass' },
    { name: 'Lime Stained Glass Pane', item: 'Lime_Stained_Glass_Pane' },
    { name: 'Lime Terracotta', item: 'Lime_Terracotta' },
    { name: 'Lime Wool', item: 'Lime_Wool' },
    { name: 'Lodestone', item: 'Lodestone' },
    { name: 'Loom', item: 'Loom' },
    { name: 'Magenta Banner', item: 'Magenta_Banner' },
    { name: 'Magenta Bed', item: 'Magenta_Bed' },
    { name: 'Magenta Candle', item: 'Magenta_Candle' },
    { name: 'Magenta Carpet', item: 'Magenta_Carpet' },
    { name: 'Magenta Concrete', item: 'Magenta_Concrete' },
    { name: 'Magenta Concrete Powder', item: 'Magenta_Concrete_Powder' },
    { name: 'Magenta Glazed Terracotta', item: 'Magenta_Glazed_Terracotta' },
    { name: 'Magenta Shulker Box', item: 'Magenta_Shulker_Box' },
    { name: 'Magenta Stained Glass', item: 'Magenta_Stained_Glass' },
    { name: 'Magenta Stained Glass Pane', item: 'Magenta_Stained_Glass_Pane' },
    { name: 'Magenta Terracotta', item: 'Magenta_Terracotta' },
    { name: 'Magenta Wool', item: 'Magenta_Wool' },
    { name: 'Magma Block', item: 'Magma_Block' },
    { name: 'Mangrove Button', item: 'Mangrove_Button' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Door', item: 'Mangrove_Door' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Fence', item: 'Mangrove_Fence' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Fence Gate', item: 'Mangrove_Fence_Gate' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Leaves', item: 'Mangrove_Leaves' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Log', item: 'Mangrove_Log' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Pressure Plate', item: 'Mangrove_Pressure_Plate' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Propagule', item: 'Mangrove_Propagule' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Planks', item: 'Mangrove_Planks' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Roots', item: 'Mangrove_Roots' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Sign', item: 'Mangrove_Sign' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Slab', item: 'Mangrove_Slab' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Stairs', item: 'Mangrove_Stairs' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Trapdoor', item: 'Mangrove_Trapdoor' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mangrove Wood', item: 'Mangrove_Wood' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Medium Amethyst Bud', item: 'Medium_Amethyst_Bud' },
    { name: 'Melon', item: 'Melon' },
    { name: 'Melon Stem', item: 'Melon_Stem' },
    { name: 'Moss Block', item: 'Moss_Block' },
    { name: 'Moss Carpet', item: 'Moss_Carpet' },
    { name: 'Mossy Cobblestone', item: 'Mossy_Cobblestone' },
    { name: 'Mossy Cobblestone Slab', item: 'Mossy_Cobblestone_Slab' },
    { name: 'Mossy Cobblestone Stairs', item: 'Mossy_Cobblestone_Stairs' },
    { name: 'Mossy Cobblestone Wall', item: 'Mossy_Cobblestone_Wall' },
    { name: 'Mossy Stone Brick Slab', item: 'Mossy_Stone_Brick_Slab' },
    { name: 'Mossy Stone Brick Stairs', item: 'Mossy_Stone_Brick_Stairs' },
    { name: 'Mossy Stone Brick Wall', item: 'Mossy_Stone_Brick_Wall' },
    { name: 'Mossy Stone Bricks', item: 'Mossy_Stone_Bricks' },
    { name: 'Mud', item: 'Mud' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mud Brick Slab', item: 'Mud_Brick_Slab' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mud Brick Stairs', item: 'Mud_Brick_Stairs' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mud Brick Wall', item: 'Mud_Brick_Wall' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mud Bricks', item: 'Mud_Bricks' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Muddy Mangrove Roots', item: 'Muddy_Mangrove_Roots' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Mushroom Stem', item: 'Mushroom_Stem' },
    { name: 'Mycelium', item: 'Mycelium' },
    { name: 'Nether Brick Fence', item: 'Nether_Brick_Fence' },
    { name: 'Nether Brick Slab', item: 'Nether_Brick_Slab' },
    { name: 'Nether Brick Stairs', item: 'Nether_Brick_Stairs' },
    { name: 'Nether Brick Wall', item: 'Nether_Brick_Wall' },
    { name: 'Nether Bricks', item: 'Nether_Bricks' },
    { name: 'Nether Gold Ore', item: 'Nether_Gold_Ore' },
    { name: 'Nether Quartz Ore', item: 'Nether_Quartz_Ore' },
    { name: 'Nether Reactor Core', item: 'Nether_Reactor_Core' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Nether Sprouts', item: 'Nether_Sprouts' },
    { name: 'Nether Wart', item: 'Nether_Wart' },
    { name: 'Nether Wart Block', item: 'Nether_Wart_Block' },
    { name: 'Netherrack', item: 'Netherrack' },
    { name: 'Note Block', item: 'Note_Block' },
    { name: 'Oak Button', item: 'Oak_Button' },
    { name: 'Oak Door', item: 'Oak_Door' },
    { name: 'Oak Fence', item: 'Oak_Fence' },
    { name: 'Oak Fence Gate', item: 'Oak_Fence_Gate' },
    { name: 'Oak Leaves', item: 'Oak_Leaves' },
    { name: 'Oak Log', item: 'Oak_Log' },
    { name: 'Oak Planks', item: 'Oak_Planks' },
    { name: 'Oak Pressure Plate', item: 'Oak_Pressure_Plate' },
    { name: 'Oak Sapling', item: 'Oak_Sapling' },
    { name: 'Oak Sign', item: 'Oak_Sign' },
    { name: 'Oak Slab', item: 'Oak_Slab' },
    { name: 'Oak Stairs', item: 'Oak_Stairs' },
    { name: 'Oak Trapdoor', item: 'Oak_Trapdoor' },
    { name: 'Oak Wood', item: 'Oak_Wood' },
    { name: 'Observer', item: 'Observer' },
    { name: 'Obsidian', item: 'Obsidian' },
    { name: 'Ochre Froglight', item: 'Ochre_Froglight' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Ominous Banner', item: 'Ominous_Banner' },
    { name: 'Orange Banner', item: 'Orange_Banner' },
    { name: 'Orange Bed', item: 'Orange_Bed' },
    { name: 'Orange Candle', item: 'Orange_Candle' },
    { name: 'Orange Carpet', item: 'Orange_Carpet' },
    { name: 'Orange Concrete', item: 'Orange_Concrete' },
    { name: 'Orange Concrete Powder', item: 'Orange_Concrete_Powder' },
    { name: 'Orange Glazed Terracotta', item: 'Orange_Glazed_Terracotta' },
    { name: 'Orange Shulker Box', item: 'Orange_Shulker_Box' },
    { name: 'Orange Stained Glass', item: 'Orange_Stained_Glass' },
    { name: 'Orange Stained Glass Pane', item: 'Orange_Stained_Glass_Pane' },
    { name: 'Orange Terracotta', item: 'Orange_Terracotta' },
    { name: 'Orange Tulip', item: 'Orange_Tulip' },
    { name: 'Orange Wool', item: 'Orange_Wool' },
    { name: 'Oxeye Daisy', item: 'Oxeye_Daisy' },
    { name: 'Oxidized Copper', item: 'Oxidized_Copper' },
    { name: 'Oxidized Cut Copper', item: 'Oxidized_Cut_Copper' },
    { name: 'Oxidized Cut Copper Slab', item: 'Oxidized_Cut_Copper_Slab' },
    { name: 'Oxidized Cut Copper Stairs', item: 'Oxidized_Cut_Copper_Stairs' },
    { name: 'Packed Ice', item: 'Packed_Ice' },
    { name: 'Packed Mud', item: 'Packed_Mud' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Pearlescent Froglight', item: 'Pearlescent_Froglight' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Peony', item: 'Peony' },
    { name: 'Petrified Oak Slab', item: 'Petrified_Oak_Slab' },
    { name: 'Pink Banner', item: 'Pink_Banner' },
    { name: 'Pink Bed', item: 'Pink_Bed' },
    { name: 'Pink Candle', item: 'Pink_Candle' },
    { name: 'Pink Carpet', item: 'Pink_Carpet' },
    { name: 'Pink Concrete', item: 'Pink_Concrete' },
    { name: 'Pink Concrete Powder', item: 'Pink_Concrete_Powder' },
    { name: 'Pink Glazed Terracotta', item: 'Pink_Glazed_Terracotta' },
    { name: 'Pink Shulker Box', item: 'Pink_Shulker_Box' },
    { name: 'Pink Stained Glass', item: 'Pink_Stained_Glass' },
    { name: 'Pink Stained Glass Pane', item: 'Pink_Stained_Glass_Pane' },
    { name: 'Pink Terracotta', item: 'Pink_Terracotta' },
    { name: 'Pink Tulip', item: 'Pink_Tulip' },
    { name: 'Pink Wool', item: 'Pink_Wool' },
    { name: 'Piston', item: 'Piston' },
    { name: 'Player Head', item: 'Player_Head' },
    { name: 'Podzol', item: 'Podzol' },
    { name: 'Pointed Dripstone', item: 'Pointed_Dripstone' },
    { name: 'Polished Andesite', item: 'Polished_Andesite' },
    { name: 'Polished Andesite Slab', item: 'Polished_Andesite_Slab' },
    { name: 'Polished Andesite Stairs', item: 'Polished_Andesite_Stairs' },
    { name: 'Polished Basalt', item: 'Polished_Basalt' },
    { name: 'Polished Blackstone', item: 'Polished_Blackstone' },
    { name: 'Polished Blackstone Brick Slab', item: 'Polished_Blackstone_Brick_Slab' },
    { name: 'Polished Blackstone Brick Stairs', item: 'Polished_Blackstone_Brick_Stairs' },
    { name: 'Polished Blackstone Brick Wall', item: 'Polished_Blackstone_Brick_Wall' },
    { name: 'Polished Blackstone Bricks', item: 'Polished_Blackstone_Bricks' },
    { name: 'Polished Blackstone Button', item: 'Polished_Blackstone_Button' },
    { name: 'Polished Blackstone Pressure Plate', item: 'Polished_Blackstone_Pressure_Plate' },
    { name: 'Polished Blackstone Slab', item: 'Polished_Blackstone_Slab' },
    { name: 'Polished Blackstone Stairs', item: 'Polished_Blackstone_Stairs' },
    { name: 'Polished Blackstone Wall', item: 'Polished_Blackstone_Wall' },
    { name: 'Polished Diorite', item: 'Polished_Diorite' },
    { name: 'Polished Diorite Slab', item: 'Polished_Diorite_Slab' },
    { name: 'Polished Diorite Stairs', item: 'Polished_Diorite_Stairs' },
    { name: 'Polished Granite', item: 'Polished_Granite' },
    { name: 'Polished Granite Slab', item: 'Polished_Granite_Slab' },
    { name: 'Polished Granite Stairs', item: 'Polished_Granite_Stairs' },
    { name: 'Polished Deepslate', item: 'Polished_Deepslate' },
    { name: 'Polished Deepslate Slab', item: 'Polished_Deepslate_Slab' },
    { name: 'Polished Deepslate Stairs', item: 'Polished_Deepslate_Stairs' },
    { name: 'Polished Deepslate Wall', item: 'Polished_Deepslate_Wall' },
    { name: 'Poppy', item: 'Poppy' },
    { name: 'Potatoes', item: 'Potato' },
    { name: 'Powder Snow', item: 'Powder_Snow' },
    { name: 'Powered Rail', item: 'Powered_Rail' },
    { name: 'Prismarine', item: 'Prismarine' },
    { name: 'Prismarine Brick Slab', item: 'Prismarine_Brick_Slab' },
    { name: 'Prismarine Brick Stairs', item: 'Prismarine_Brick_Stairs' },
    { name: 'Prismarine Bricks', item: 'Prismarine_Bricks' },
    { name: 'Prismarine Slab', item: 'Prismarine_Slab' },
    { name: 'Prismarine Stairs', item: 'Prismarine_Stairs' },
    { name: 'Prismarine Wall', item: 'Prismarine_Wall' },
    { name: 'Pumpkin', item: 'Pumpkin' },
    { name: 'Pumpkin Stem', item: 'Pumpkin_Stem' },
    { name: 'Purple Banner', item: 'Purple_Banner' },
    { name: 'Purple Bed', item: 'Purple_Bed' },
    { name: 'Purple Candle', item: 'Purple_Candle' },
    { name: 'Purple Carpet', item: 'Purple_Carpet' },
    { name: 'Purple Concrete', item: 'Purple_Concrete' },
    { name: 'Purple Concrete Powder', item: 'Purple_Concrete_Powder' },
    { name: 'Purple Glazed Terracotta', item: 'Purple_Glazed_Terracotta' },
    { name: 'Purple Shulker Box', item: 'Purple_Shulker_Box' },
    { name: 'Purple Stained Glass', item: 'Purple_Stained_Glass' },
    { name: 'Purple Stained Glass Pane', item: 'Purple_Stained_Glass_Pane' },
    { name: 'Purple Terracotta', item: 'Purple_Terracotta' },
    { name: 'Purple Wool', item: 'Purple_Wool' },
    { name: 'Purpur Block', item: 'Purpur_Block' },
    { name: 'Purpur Pillar', item: 'Purpur_Pillar' },
    { name: 'Purpur Slab', item: 'Purpur_Slab' },
    { name: 'Purpur Stairs', item: 'Purpur_Stairs' },
    { name: 'Quartz Bricks', item: 'Quartz_Bricks' },
    { name: 'Quartz Pillar', item: 'Quartz_Pillar' },
    { name: 'Quartz Slab', item: 'Quartz_Slab' },
    { name: 'Quartz Stairs', item: 'Quartz_Stairs' },
    { name: 'Rail', item: 'Rail' },
    { name: 'Red Banner', item: 'Red_Banner' },
    { name: 'Red Bed', item: 'Red_Bed' },
    { name: 'Red Candle', item: 'Red_Candle' },
    { name: 'Red Carpet', item: 'Red_Carpet' },
    { name: 'Red Concrete', item: 'Red_Concrete' },
    { name: 'Red Concrete Powder', item: 'Red_Concrete_Powder' },
    { name: 'Red Glazed Terracotta', item: 'Red_Glazed_Terracotta' },
    { name: 'Red Mushroom', item: 'Red_Mushroom' },
    { name: 'Red Mushroom Block', item: 'Red_Mushroom_Block' },
    { name: 'Red Nether Brick Slab', item: 'Red_Nether_Brick_Slab' },
    { name: 'Red Nether Brick Stairs', item: 'Red_Nether_Brick_Stairs' },
    { name: 'Red Nether Brick Wall', item: 'Red_Nether_Brick_Wall' },
    { name: 'Red Nether Bricks', item: 'Red_Nether_Bricks' },
    { name: 'Red Sand', item: 'Red_Sand' },
    { name: 'Red Sandstone', item: 'Red_Sandstone' },
    { name: 'Red Sandstone Slab', item: 'Red_Sandstone_Slab' },
    { name: 'Red Sandstone Stairs', item: 'Red_Sandstone_Stairs' },
    { name: 'Red Sandstone Wall', item: 'Red_Sandstone_Wall' },
    { name: 'Red Shulker Box', item: 'Red_Shulker_Box' },
    { name: 'Red Stained Glass', item: 'Red_Stained_Glass' },
    { name: 'Red Stained Glass Pane', item: 'Red_Stained_Glass_Pane' },
    { name: 'Red Terracotta', item: 'Red_Terracotta' },
    { name: 'Red Tulip', item: 'Red_Tulip' },
    { name: 'Red Wool', item: 'Red_Wool' },
    { name: 'Redstone Comparator', item: 'Redstone_Comparator' },
    { name: 'Redstone Lamp', item: 'Redstone_Lamp' },
    { name: 'Redstone Ore', item: 'Redstone_Ore' },
    { name: 'Redstone Repeater', item: 'Redstone_Repeater' },
    { name: 'Redstone Torch', item: 'Redstone_Torch' },
    { name: 'Redstone Wire', item: 'Redstone_Wire' },
    { name: 'Reinforced Deepslate', item: 'Reinforced_Deepslate' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Repeating Command Block', item: 'Repeating_Command_Block' },
    { name: 'Respawn Anchor', item: 'Respawn_Anchor' },
    { name: 'Rooted Dirt', item: 'Rooted_Dirt' },
    { name: 'Rose Bush', item: 'Rose_Bush' },
    { name: 'Sand', item: 'Sand' },
    { name: 'Sandstone', item: 'Sandstone' },
    { name: 'Sandstone Slab', item: 'Sandstone_Slab' },
    { name: 'Sandstone Stairs', item: 'Sandstone_Stairs' },
    { name: 'Sandstone Wall', item: 'Sandstone_Wall' },
    { name: 'Scaffolding', item: 'Scaffolding' },
    { name: 'Sculk', item: 'Sculk' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Sculk Catalyst', item: 'Sculk_Catalyst' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Sculk Sensor', item: 'Sculk_Sensor' },
    { name: 'Sculk Shrieker', item: 'Sculk_Shrieker' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Sculk Vein', item: 'Sculk_Vein' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Sea Lantern', item: 'Sea_Lantern' },
    { name: 'Sea Pickle', item: 'Sea_Pickle' },
    { name: 'Seagrass', item: 'Seagrass' },
    { name: 'Shroomlight', item: 'Shroomlight' },
    { name: 'Shulker Box', item: 'Shulker_Box' },
    { name: 'Skeleton Skull', item: 'Skeleton_Skull' },
    { name: 'Slime Block', item: 'Slime_Block' },
    { name: 'Small Amethyst Bud', item: 'Small_Amethyst_Bud' },
    { name: 'Small Dripleaf', item: 'Small_Dripleaf' },
    { name: 'Smithing Table', item: 'Smithing_Table' },
    { name: 'Smoker', item: 'Smoker' },
    { name: 'Smooth Basalt', item: 'Smooth_Basalt' },
    { name: 'Smooth Quartz Block', item: 'Smooth_Quartz_Block' },
    { name: 'Smooth Quartz Slab', item: 'Smooth_Quartz_Slab' },
    { name: 'Smooth Quartz Stairs', item: 'Smooth_Quartz_Stairs' },
    { name: 'Smooth Red Sandstone', item: 'Smooth_Red_Sandstone' },
    { name: 'Smooth Red Sandstone Slab', item: 'Smooth_Red_Sandstone_Slab' },
    { name: 'Smooth Red Sandstone Stairs', item: 'Smooth_Red_Sandstone_Stairs' },
    { name: 'Smooth Sandstone', item: 'Smooth_Sandstone' },
    { name: 'Smooth Sandstone Slab', item: 'Smooth_Sandstone_Slab' },
    { name: 'Smooth Sandstone Stairs', item: 'Smooth_Sandstone_Stairs' },
    { name: 'Smooth Stone', item: 'Smooth_Stone' },
    { name: 'Smooth Stone Slab', item: 'Smooth_Stone_Slab' },
    { name: 'Snow', item: 'Snow' },
    { name: 'Snow Block', item: 'Snow_Block' },
    { name: 'Soul Campfire', item: 'Soul_Campfire' },
    { name: 'Soul Fire', item: 'Soul_Fire' },
    { name: 'Soul Lantern', item: 'Soul_Lantern' },
    { name: 'Soul Sand', item: 'Soul_Sand' },
    { name: 'Soul Soil', item: 'Soul_Soil' },
    { name: 'Soul Torch', item: 'Soul_Torch' },
    { name: 'Spawner', item: 'Spawner' },
    { name: 'Sponge', item: 'Sponge' },
    { name: 'Spore Blossom', item: 'Spore_Blossom' },
    { name: 'Spruce Button', item: 'Spruce_Button' },
    { name: 'Spruce Door', item: 'Spruce_Door' },
    { name: 'Spruce Fence', item: 'Spruce_Fence' },
    { name: 'Spruce Fence Gate', item: 'Spruce_Fence_Gate' },
    { name: 'Spruce Leaves', item: 'Spruce_Leaves' },
    { name: 'Spruce Log', item: 'Spruce_Log' },
    { name: 'Spruce Planks', item: 'Spruce_Planks' },
    { name: 'Spruce Pressure Plate', item: 'Spruce_Pressure_Plate' },
    { name: 'Spruce Sapling', item: 'Spruce_Sapling' },
    { name: 'Spruce Sign', item: 'Spruce_Sign' },
    { name: 'Spruce Slab', item: 'Spruce_Slab' },
    { name: 'Spruce Stairs', item: 'Spruce_Stairs' },
    { name: 'Spruce Trapdoor', item: 'Spruce_Trapdoor' },
    { name: 'Spruce Wood', item: 'Spruce_Wood' },
    { name: 'Sticky Piston', item: 'Sticky_Piston' },
    { name: 'Stone', item: 'Stone' },
    { name: 'Stone Brick Slab', item: 'Stone_Brick_Slab' },
    { name: 'Stone Brick Stairs', item: 'Stone_Brick_Stairs' },
    { name: 'Stone Brick Wall', item: 'Stone_Brick_Wall' },
    { name: 'Stone Bricks', item: 'Stone_Bricks' },
    { name: 'Stone Button', item: 'Stone_Button' },
    { name: 'Stone Pressure Plate', item: 'Stone_Pressure_Plate' },
    { name: 'Stone Slab', item: 'Stone_Slab' },
    { name: 'Stone Stairs', item: 'Stone_Stairs' },
    { name: 'Stonecutter', item: 'Stonecutter' },
    { name: 'Stonecutter', item: 'Stonecutter/old' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Stripped Acacia Log', item: 'Stripped_Acacia_Log' },
    { name: 'Stripped Acacia Wood', item: 'Stripped_Acacia_Wood' },
    { name: 'Stripped Birch Log', item: 'Stripped_Birch_Log' },
    { name: 'Stripped Birch Wood', item: 'Stripped_Birch_Wood' },
    { name: 'Stripped Crimson Hyphae', item: 'Stripped_Crimson_Hyphae' },
    { name: 'Stripped Crimson Stem', item: 'Stripped_Crimson_Stem' },
    { name: 'Stripped Dark Oak Log', item: 'Stripped_Dark_Oak_Log' },
    { name: 'Stripped Dark Oak Wood', item: 'Stripped_Dark_Oak_Wood' },
    { name: 'Stripped Jungle Log', item: 'Stripped_Jungle_Log' },
    { name: 'Stripped Jungle Wood', item: 'Stripped_Jungle_Wood' },
    { name: 'Stripped Mangrove Log', item: 'Stripped_Mangrove_Log' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Stripped Mangrove Wood', item: 'Stripped_Mangrove_Wood' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Stripped Oak Log', item: 'Stripped_Oak_Log' },
    { name: 'Stripped Oak Wood', item: 'Stripped_Oak_Wood' },
    { name: 'Stripped Spruce Log', item: 'Stripped_Spruce_Log' },
    { name: 'Stripped Spruce Wood', item: 'Stripped_Spruce_Wood' },
    { name: 'Stripped Warped Hyphae', item: 'Stripped_Warped_Hyphae' },
    { name: 'Stripped Warped Stem', item: 'Stripped_Warped_Stem' },
    { name: 'Structure Block', item: 'Structure_Block' },
    { name: 'Structure Void', item: 'Structure_Void' },
    { name: 'Sugar Cane', item: 'Sugar_Cane' },
    { name: 'Sunflower', item: 'Sunflower' },
    { name: 'Sweet Berry Bush', item: 'Sweet_Berry_Bush' },
    { name: 'Tall Grass', item: 'Tall_Grass' },
    { name: 'Tall Seagrass', item: 'Tall_Seagrass' },
    { name: 'Target', item: 'Target' },
    { name: 'Terracotta', item: 'Terracotta' },
    { name: 'Tinted Glass', item: 'Tinted_Glass' },
    { name: 'TNT', item: 'TNT' },
    { name: 'Torch', item: 'Torch' },
    { name: 'Trapped Chest', item: 'Trapped_Chest' },
    { name: 'Tripwire', item: 'Tripwire' },
    { name: 'Tripwire Hook', item: 'Tripwire_Hook' },
    { name: 'Tube Coral', item: 'Tube_Coral' },
    { name: 'Tube Coral Block', item: 'Tube_Coral_Block' },
    { name: 'Tube Coral Fan', item: 'Tube_Coral_Fan' },
    { name: 'Tuff', item: 'Tuff' },
    { name: 'Turtle Egg', item: 'Turtle_Egg' },
    { name: 'Twisting Vines', item: 'Twisting_Vines' },
    { name: 'Verdant Froglight', item: 'Verdant_Froglight' },
    { name: 'upcoming', item: 'Planned_versions' },
    { name: 'Vines', item: 'Vines' },
    { name: 'Warped Button', item: 'Warped_Button' },
    { name: 'Warped Door', item: 'Warped_Door' },
    { name: 'Warped Fence', item: 'Warped_Fence' },
    { name: 'Warped Fence Gate', item: 'Warped_Fence_Gate' },
    { name: 'Warped Fungus', item: 'Warped_Fungus' },
    { name: 'Warped Hyphae', item: 'Warped_Hyphae' },
    { name: 'Warped Nylium', item: 'Warped_Nylium' },
    { name: 'Warped Planks', item: 'Warped_Planks' },
    { name: 'Warped Pressure Plate', item: 'Warped_Pressure_Plate' },
    { name: 'Warped Roots', item: 'Warped_Roots' },
    { name: 'Warped Sign', item: 'Warped_Sign' },
    { name: 'Warped Slab', item: 'Warped_Slab' },
    { name: 'Warped Stairs', item: 'Warped_Stairs' },
    { name: 'Warped Stem', item: 'Warped_Stem' },
    { name: 'Warped Trapdoor', item: 'Warped_Trapdoor' },
    { name: 'Warped Wart Block', item: 'Warped_Wart_Block' },
    { name: 'Water', item: 'Water' },
    { name: 'Waxed Block of Copper', item: 'Waxed_Block_of_Copper' },
    { name: 'Waxed Cut Copper', item: 'Waxed_Cut_Copper' },
    { name: 'Waxed Cut Copper Slab', item: 'Waxed_Cut_Copper_Slab' },
    { name: 'Waxed Cut Copper Stairs', item: 'Waxed_Cut_Copper_Stairs' },
    { name: 'Waxed Exposed Copper', item: 'Waxed_Exposed_Copper' },
    { name: 'Waxed Exposed Cut Copper', item: 'Waxed_Exposed_Cut_Copper' },
    { name: 'Waxed Exposed Cut Copper Slab', item: 'Waxed_Exposed_Cut_Copper_Slab' },
    { name: 'Waxed Exposed Cut Copper Stairs', item: 'Waxed_Exposed_Cut_Copper_Stairs' },
    { name: 'Waxed Oxidized Copper', item: 'Waxed_Oxidized_Copper' },
    { name: 'Waxed Oxidized Cut Copper', item: 'Waxed_Oxidized_Cut_Copper' },
    { name: 'Waxed Oxidized Cut Copper Slab', item: 'Waxed_Oxidized_Cut_Copper_Slab' },
    { name: 'Waxed Oxidized Cut Copper Stairs', item: 'Waxed_Oxidized_Cut_Copper_Stairs' },
    { name: 'Waxed Weathered Copper', item: 'Waxed_Weathered_Copper' },
    { name: 'Waxed Weathered Cut Copper', item: 'Waxed_Weathered_Cut_Copper' },
    { name: 'Waxed Weathered Cut Copper Slab', item: 'Waxed_Weathered_Cut_Copper_Slab' },
    { name: 'Waxed Weathered Cut Copper Stairs', item: 'Waxed_Weathered_Cut_Copper_Stairs' },
    { name: 'Weathered Copper', item: 'Weathered_Copper' },
    { name: 'Weathered Cut Copper', item: 'Weathered_Cut_Copper' },
    { name: 'Weathered Cut Copper Slab', item: 'Weathered_Cut_Copper_Slab' },
    { name: 'Weathered Cut Copper Stairs', item: 'Weathered_Cut_Copper_Stairs' },
    { name: 'Weeping Vines', item: 'Weeping_Vines' },
    { name: 'Wet Sponge', item: 'Wet_Sponge' },
    { name: 'Wheat Crops', item: 'Wheat_Crops' },
    { name: 'White Banner', item: 'White_Banner' },
    { name: 'White Bed', item: 'White_Bed' },
    { name: 'White Candle', item: 'White_Candle' },
    { name: 'White Carpet', item: 'White_Carpet' },
    { name: 'White Concrete', item: 'White_Concrete' },
    { name: 'White Concrete Powder', item: 'White_Concrete_Powder' },
    { name: 'White Glazed Terracotta', item: 'White_Glazed_Terracotta' },
    { name: 'White Shulker Box', item: 'White_Shulker_Box' },
    { name: 'White Stained Glass', item: 'White_Stained_Glass' },
    { name: 'White Stained Glass Pane', item: 'White_Stained_Glass_Pane' },
    { name: 'White Terracotta', item: 'White_Terracotta' },
    { name: 'White Tulip', item: 'White_Tulip' },
    { name: 'White Wool', item: 'White_Wool' },
    { name: 'Wither Rose', item: 'Wither_Rose' },
    { name: 'Wither Skeleton Skull', item: 'Wither_Skeleton_Skull' },
    { name: 'Yellow Banner', item: 'Yellow_Banner' },
    { name: 'Yellow Bed', item: 'Yellow_Bed' },
    { name: 'Yellow Candle', item: 'Yellow_Candle' },
    { name: 'Yellow Carpet', item: 'Yellow_Carpet' },
    { name: 'Yellow Concrete', item: 'Yellow_Concrete' },
    { name: 'Yellow Concrete Powder', item: 'Yellow_Concrete_Powder' },
    { name: 'Yellow Glazed Terracotta', item: 'Yellow_Glazed_Terracotta' },
    { name: 'Yellow Shulker Box', item: 'Yellow_Shulker_Box' },
    { name: 'Yellow Stained Glass', item: 'Yellow_Stained_Glass' },
    { name: 'Yellow Stained Glass Pane', item: 'Yellow_Stained_Glass_Pane' },
    { name: 'Yellow Terracotta', item: 'Yellow_Terracotta' },
    { name: 'Yellow Wool', item: 'Yellow_Wool' },
    { name: 'Zombie Head', item: 'Zombie_Head' },
    { name: 'Acacia Boat', item: 'Acacia_Boat' },
    { name: 'Armor Stand', item: 'Armor_Stand' },
    { name: 'Beetroot Seeds', item: 'Beetroot_Seeds' },
    { name: 'Birch Boat', item: 'Birch_Boat' },
    { name: 'Bottle o Enchanting', item: 'Bottle_o_Enchanting' },
    { name: 'Bow', item: 'Bow' },
    { name: 'Bucket', item: 'Bucket' },
    { name: 'Bucket of Axolotl', item: 'Bucket_of_Axolotl' },
    { name: 'Bucket of Cod', item: 'Bucket_of_Cod' },
    { name: 'Bucket of Pufferfish', item: 'Bucket_of_Pufferfish' },
    { name: 'Bucket of Salmon', item: 'Bucket_of_Salmon' },
    { name: 'Bucket of Tadpole', item: 'Bucket_of_Tadpole' },
    { name: 'Java Edition 1.19', item: 'Java_Edition_1.19' },
    { name: 'Bucket of Tropical Fish', item: 'Bucket_of_Tropical_Fish' },
    { name: 'Carrot', item: 'Carrot' },
    { name: 'Cocoa Beans', item: 'Cocoa_Beans' },
    { name: 'Crossbow', item: 'Crossbow' },
    { name: 'Dark Oak Boat', item: 'Dark_Oak_Boat' },
    { name: 'Egg', item: 'Egg' },
    { name: 'End Crystal', item: 'End_Crystal' },
    { name: 'Ender Pearl', item: 'Ender_Pearl' },
    { name: 'Eye of Ender', item: 'Eye_of_Ender' },
    { name: 'Fire Charge', item: 'Fire_Charge' },
    { name: 'Firework Rocket', item: 'Firework_Rocket' },
    { name: 'Fishing Rod', item: 'Fishing_Rod' },
    { name: 'Flint and Steel', item: 'Flint_and_Steel' },
    { name: 'Glow Berries', item: 'Glow_Berries' },
    { name: 'Glow Item Frame', item: 'Glow_Item_Frame' },
    { name: 'Item Frame', item: 'Item_Frame' },
    { name: 'Jungle Boat', item: 'Jungle_Boat' },
    { name: 'Kelp', item: 'Kelp' },
    { name: 'Lava Bucket', item: 'Lava_Bucket' },
    { name: 'Lead', item: 'Lead' },
    { name: 'Lingering Potion', item: 'Lingering_Potion' },
    { name: 'Mangrove Boat', item: 'Mangrove_Boat' },
    { name: 'Java Edition 1.19', item: 'Java_Edition_1.19' },
    { name: 'Melon Seeds', item: 'Melon_Seeds' },
    { name: 'Minecart', item: 'Minecart' },
    { name: 'Minecart with Chest', item: 'Minecart_with_Chest' },
    { name: 'Minecart with Command Block', item: 'Minecart_with_Command_Block' },
    { name: 'Minecart with Furnace', item: 'Minecart_with_Furnace' },
    { name: 'Java Edition', item: 'Java_Edition' },
    { name: 'Minecart with Hopper', item: 'Minecart_with_Hopper' },
    { name: 'Minecart with TNT', item: 'Minecart_with_TNT' },
    { name: 'Nether Wart', item: 'Nether_Wart' },
    { name: 'Oak Boat', item: 'Oak_Boat' },
    { name: 'Painting', item: 'Painting' },
    { name: 'Potato', item: 'Potato' },
    { name: 'Powder Snow Bucket', item: 'Powder_Snow_Bucket' },
    { name: 'Pumpkin Seeds', item: 'Pumpkin_Seeds' },
    { name: 'Redstone Dust', item: 'Redstone_Dust' },
    { name: 'Snowball', item: 'Snowball' },
    { name: 'Splash Potion', item: 'Splash_Potion' },
    { name: 'Spruce Boat', item: 'Spruce_Boat' },
    { name: 'String', item: 'String' },
    { name: 'Sweet Berries', item: 'Sweet_Berries' },
    { name: 'Trident', item: 'Trident' },
    { name: 'Water Bucket', item: 'Water_Bucket' },
    { name: 'Wheat Seeds', item: 'Wheat_Seeds' },
    { name: 'Apple', item: 'Apple' },
    { name: 'Arrow', item: 'Arrow' },
    { name: 'Baked Potato', item: 'Baked_Potato' },
    { name: 'Beetroot', item: 'Beetroot' },
    { name: 'Beetroot Soup', item: 'Beetroot_Soup' },
    { name: 'Black Dye', item: 'Black_Dye' },
    { name: 'Blue Dye', item: 'Blue_Dye' },
    { name: 'Bone', item: 'Bone' },
    { name: 'Bone Meal', item: 'Bone_Meal' },
    { name: 'Book and Quill', item: 'Book_and_Quill' },
    { name: 'Bowl', item: 'Bowl' },
    { name: 'Bread', item: 'Bread' },
    { name: 'Brown Dye', item: 'Brown_Dye' },
    { name: 'Bundle', item: 'Bundle' },
    { name: 'Carrot on a Stick', item: 'Carrot_on_a_Stick' },
    { name: 'Chainmail Boots', item: 'Chainmail_Boots' },
    { name: 'Chainmail Chestplate', item: 'Chainmail_Chestplate' },
    { name: 'Chainmail Helmet', item: 'Chainmail_Helmet' },
    { name: 'Chainmail Leggings', item: 'Chainmail_Leggings' },
    { name: 'Chorus Fruit', item: 'Chorus_Fruit' },
    { name: 'Compass', item: 'Compass' },
    { name: 'Cooked Chicken', item: 'Cooked_Chicken' },
    { name: 'Cooked Cod', item: 'Cooked_Cod' },
    { name: 'Cooked Mutton', item: 'Cooked_Mutton' },
    { name: 'Cooked Porkchop', item: 'Cooked_Porkchop' },
    { name: 'Cooked Rabbit', item: 'Cooked_Rabbit' },
    { name: 'Cooked Salmon', item: 'Cooked_Salmon' },
    { name: 'Cookie', item: 'Cookie' },
    { name: 'Cyan Dye', item: 'Cyan_Dye' },
    { name: 'Debug Stick', item: 'Debug_Stick' },
    { name: 'Java Edition', item: 'Java_Edition' },
    { name: 'Diamond Axe', item: 'Diamond_Axe' },
    { name: 'Diamond Boots', item: 'Diamond_Boots' },
    { name: 'Diamond Chestplate', item: 'Diamond_Chestplate' },
    { name: 'Diamond Helmet', item: 'Diamond_Helmet' },
    { name: 'Diamond Hoe', item: 'Diamond_Hoe' },
    { name: 'Diamond Horse Armor', item: 'Diamond_Horse_Armor' },
    { name: 'Diamond Leggings', item: 'Diamond_Leggings' },
    { name: 'Diamond Pickaxe', item: 'Diamond_Pickaxe' },
    { name: 'Diamond Shovel', item: 'Diamond_Shovel' },
    { name: 'Diamond Sword', item: 'Diamond_Sword' },
    { name: 'Dried Kelp', item: 'Dried_Kelp' },
    { name: 'Elytra', item: 'Elytra' },
    { name: 'Empty Map', item: 'Empty_Map' },
    { name: 'Enchanted Golden Apple', item: 'Enchanted_Golden_Apple' },
    { name: 'Goat Horn', item: 'Goat_Horn' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Glass Bottle', item: 'Glass_Bottle' },
    { name: 'Glow Ink Sac', item: 'Glow_Ink_Sac' },
    { name: 'Gold Ingot', item: 'Gold_Ingot' },
    { name: 'Golden Apple', item: 'Golden_Apple' },
    { name: 'Golden Axe', item: 'Golden_Axe' },
    { name: 'Golden Boots', item: 'Golden_Boots' },
    { name: 'Golden Carrot', item: 'Golden_Carrot' },
    { name: 'Golden Chestplate', item: 'Golden_Chestplate' },
    { name: 'Golden Helmet', item: 'Golden_Helmet' },
    { name: 'Golden Hoe', item: 'Golden_Hoe' },
    { name: 'Golden Horse Armor', item: 'Golden_Horse_Armor' },
    { name: 'Golden Leggings', item: 'Golden_Leggings' },
    { name: 'Golden Pickaxe', item: 'Golden_Pickaxe' },
    { name: 'Golden Shovel', item: 'Golden_Shovel' },
    { name: 'Golden Sword', item: 'Golden_Sword' },
    { name: 'Gray Dye', item: 'Gray_Dye' },
    { name: 'Green Dye', item: 'Green_Dye' },
    { name: 'Honeycomb', item: 'Honeycomb' },
    { name: 'Honey Bottle', item: 'Honey_Bottle' },
    { name: 'Ink Sac', item: 'Ink_Sac' },
    { name: 'Iron Axe', item: 'Iron_Axe' },
    { name: 'Iron Boots', item: 'Iron_Boots' },
    { name: 'Iron Chestplate', item: 'Iron_Chestplate' },
    { name: 'Iron Helmet', item: 'Iron_Helmet' },
    { name: 'Iron Hoe', item: 'Iron_Hoe' },
    { name: 'Iron Horse Armor', item: 'Iron_Horse_Armor' },
    { name: 'Iron Ingot', item: 'Iron_Ingot#Healing_iron_golems' },
    { name: 'Iron Leggings', item: 'Iron_Leggings' },
    { name: 'Iron Pickaxe', item: 'Iron_Pickaxe' },
    { name: 'Iron Shovel', item: 'Iron_Shovel' },
    { name: 'Iron Sword', item: 'Iron_Sword' },
    { name: 'Knowledge Book', item: 'Knowledge_Book' },
    { name: 'Java Edition', item: 'Java_Edition' },
    { name: 'Lapis Lazuli', item: 'Lapis_Lazuli#Dye' },
    { name: 'Bedrock Edition', item: 'Bedrock_Edition' },
    { name: 'Leather Boots', item: 'Leather_Boots' },
    { name: 'Leather Cap', item: 'Leather_Cap' },
    { name: 'Leather Horse Armor', item: 'Leather_Horse_Armor' },
    { name: 'Leather Pants', item: 'Leather_Pants' },
    { name: 'Leather Tunic', item: 'Leather_Tunic' },
    { name: 'Light Blue Dye', item: 'Light_Blue_Dye' },
    { name: 'Light Gray Dye', item: 'Light_Gray_Dye' },
    { name: 'Lime Dye', item: 'Lime_Dye' },
    { name: 'Magenta Dye', item: 'Magenta_Dye' },
    { name: 'Map', item: 'Map' },
    { name: 'Explorer Map', item: 'Explorer_Map' },
    { name: 'Melon Slice', item: 'Melon_Slice' },
    { name: 'Milk Bucket', item: 'Milk_Bucket' },
    { name: 'Mushroom Stew', item: 'Mushroom_Stew' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Music Disc', item: 'Music_Disc' },
    { name: 'Name Tag', item: 'Name_Tag' },
    { name: 'Netherite Axe', item: 'Netherite_Axe' },
    { name: 'Netherite Boots', item: 'Netherite_Boots' },
    { name: 'Netherite Chestplate', item: 'Netherite_Chestplate' },
    { name: 'Netherite Helmet', item: 'Netherite_Helmet' },
    { name: 'Netherite Hoe', item: 'Netherite_Hoe' },
    { name: 'Netherite Leggings', item: 'Netherite_Leggings' },
    { name: 'Netherite Pickaxe', item: 'Netherite_Pickaxe' },
    { name: 'Netherite Shovel', item: 'Netherite_Shovel' },
    { name: 'Netherite Sword', item: 'Netherite_Sword' },
    { name: 'Orange Dye', item: 'Orange_Dye' },
    { name: 'Pink Dye', item: 'Pink_Dye' },
    { name: 'Poisonous Potato', item: 'Poisonous_Potato' },
    { name: 'Potion', item: 'Potion' },
    { name: 'Pufferfish (item)', item: 'Pufferfish_(item)' },
    { name: 'Pumpkin Pie', item: 'Pumpkin_Pie' },
    { name: 'Purple Dye', item: 'Purple_Dye' },
    { name: 'Rabbit Stew', item: 'Rabbit_Stew' },
    { name: 'Raw Beef', item: 'Raw_Beef' },
    { name: 'Raw Chicken', item: 'Raw_Chicken' },
    { name: 'Raw Cod', item: 'Raw_Cod' },
    { name: 'Raw Mutton', item: 'Raw_Mutton' },
    { name: 'Raw Porkchop', item: 'Raw_Porkchop' },
    { name: 'Raw Rabbit', item: 'Raw_Rabbit' },
    { name: 'Raw Salmon', item: 'Raw_Salmon' },
    { name: 'Red Dye', item: 'Red_Dye' },
    { name: 'Rotten Flesh', item: 'Rotten_Flesh' },
    { name: 'Saddle', item: 'Saddle' },
    { name: 'Shears', item: 'Shears' },
    { name: 'Shield', item: 'Shield' },
    { name: 'Spectral Arrow', item: 'Spectral_Arrow' },
    { name: 'Java Edition', item: 'Java_Edition' },
    { name: 'Spider Eye', item: 'Spider_Eye' },
    { name: 'Spyglass', item: 'Spyglass' },
    { name: 'Steak', item: 'Steak' },
    { name: 'Stone Axe', item: 'Stone_Axe' },
    { name: 'Stone Hoe', item: 'Stone_Hoe' },
    { name: 'Stone Pickaxe', item: 'Stone_Pickaxe' },
    { name: 'Stone Shovel', item: 'Stone_Shovel' },
    { name: 'Stone Sword', item: 'Stone_Sword' },
    { name: 'Sugar', item: 'Sugar' },
    { name: 'Suspicious Stew', item: 'Suspicious_Stew' },
    { name: 'Tipped Arrow', item: 'Tipped_Arrow' },
    { name: 'Totem of Undying', item: 'Totem_of_Undying' },
    { name: 'Tropical Fish', item: 'Tropical_Fish' },
    { name: 'Turtle Shell', item: 'Turtle_Shell' },
    { name: 'Warped Fungus on a Stick', item: 'Warped_Fungus_on_a_Stick' },
    { name: 'Wheat', item: 'Wheat' },
    { name: 'White Dye', item: 'White_Dye' },
    { name: 'Wooden Axe', item: 'Wooden_Axe' },
    { name: 'Wooden Hoe', item: 'Wooden_Hoe' },
    { name: 'Wooden Pickaxe', item: 'Wooden_Pickaxe' },
    { name: 'Wooden Shovel', item: 'Wooden_Shovel' },
    { name: 'Wooden Sword', item: 'Wooden_Sword' },
    { name: 'Written Book', item: 'Written_Book' },
    { name: 'Yellow Dye', item: 'Yellow_Dye' },
    { name: 'Amethyst Shard', item: 'Amethyst_Shard' },
    { name: 'Banner Pattern', item: 'Banner_Pattern' },
    { name: 'Banner Pattern', item: 'Banner_Pattern' },
    { name: 'Banner Pattern', item: 'Banner_Pattern' },
    { name: 'Banner Pattern', item: 'Banner_Pattern' },
    { name: 'Banner Pattern', item: 'Banner_Pattern' },
    { name: 'Banner Pattern', item: 'Banner_Pattern' },
    { name: 'Blaze Powder', item: 'Blaze_Powder' },
    { name: 'Blaze Rod', item: 'Blaze_Rod' },
    { name: 'Book', item: 'Book' },
    { name: 'Brick', item: 'Brick' },
    { name: 'Charcoal', item: 'Charcoal' },
    { name: 'Clay Ball', item: 'Clay_Ball' },
    { name: 'Clock', item: 'Clock' },
    { name: 'Coal', item: 'Coal' },
    { name: 'Copper Ingot', item: 'Copper_Ingot' },
    { name: 'Diamond', item: 'Diamond' },
    { name: 'Dragons Breath', item: 'Dragons_Breath' },
    { name: 'Emerald', item: 'Emerald' },
    { name: 'Enchanted Book', item: 'Enchanted_Book' },
    { name: 'Feather', item: 'Feather' },
    { name: 'Fermented Spider Eye', item: 'Fermented_Spider_Eye' },
    { name: 'Firework Star', item: 'Firework_Star' },
    { name: 'Flint', item: 'Flint' },
    { name: 'Ghast Tear', item: 'Ghast_Tear' },
    { name: 'Glistering Melon Slice', item: 'Glistering_Melon_Slice' },
    { name: 'Glowstone Dust', item: 'Glowstone_Dust' },
    { name: 'Gold Nugget', item: 'Gold_Nugget' },
    { name: 'Gunpowder', item: 'Gunpowder' },
    { name: 'Heart of the Sea', item: 'Heart_of_the_Sea' },
    { name: 'Ink Sac', item: 'Ink_Sac' },
    { name: 'Iron Ingot', item: 'Iron_Ingot' },
    { name: 'Iron Nugget', item: 'Iron_Nugget' },
    { name: 'Lapis Lazuli', item: 'Lapis_Lazuli' },
    { name: 'Leather', item: 'Leather' },
    { name: 'Magma Cream', item: 'Magma_Cream' },
    { name: 'Nautilus Shell', item: 'Nautilus_Shell' },
    { name: 'Nether Brick', item: 'Nether_Brick' },
    { name: 'Nether Quartz', item: 'Nether_Quartz' },
    { name: 'Nether Star', item: 'Nether_Star' },
    { name: 'Netherite Ingot', item: 'Netherite_Ingot' },
    { name: 'Netherite Scrap', item: 'Netherite_Scrap' },
    { name: 'Paper', item: 'Paper' },
    { name: 'Phantom Membrane', item: 'Phantom_Membrane' },
    { name: 'Popped Chorus Fruit', item: 'Popped_Chorus_Fruit' },
    { name: 'Prismarine Crystals', item: 'Prismarine_Crystals' },
    { name: 'Prismarine Shard', item: 'Prismarine_Shard' },
    { name: 'Rabbit Hide', item: 'Rabbit_Hide' },
    { name: 'Rabbits Foot', item: 'Rabbits_Foot' },
    { name: 'Raw Copper', item: 'Raw_Copper' },
    { name: 'Raw Gold', item: 'Raw_Gold' },
    { name: 'Raw Iron', item: 'Raw_Iron' },
    { name: 'Scute', item: 'Scute' },
    { name: 'Shulker Shell', item: 'Shulker_Shell' },
    { name: 'Slimeball', item: 'Slimeball' },
    { name: 'Stick', item: 'Stick' }

  ]
}
